export type SubjectKey = "korean" | "english" | "math";

export type StudyTask = {
  id: string;
  subject: SubjectKey;
  title: string;
  description: string;
  duration: number;
  destination: "roadmap" | "notes" | "vocab";
};

export type RoadmapUnit = {
  id: string;
  week: number;
  phase: string;
  title: string;
  goal: string;
  summaryKeyPoints?: string[];
  learn: string[];
  routine: string[];
  checkpoint: string;
  noteIds: string[];
  youtubeUrl?: string;
};

export type CoreNote = {
  id: string;
  subject: SubjectKey;
  category: string;
  title: string;
  oneLine: string;
  essentials: string[];
  formula?: string;
  mistake: string;
  microPractice: string;
  youtubeUrl?: string;
};

export type SubjectGuide = {
  label: string;
  shortLabel: string;
  eyebrow: string;
  promise: string;
  method: string[];
  weeklyRule: string;
};

export const SUBJECT_KEYS: SubjectKey[] = ["korean", "english", "math"];

export const SUBJECT_GUIDES: Record<SubjectKey, SubjectGuide> = {
  korean: {
    label: "국어",
    shortLabel: "국",
    eyebrow: "문장을 읽는 순서부터",
    promise: "감으로 고르지 않고, 지문 안에서 답의 근거를 찾는 힘을 만듭니다.",
    method: [
      "문장을 주어·서술어 중심으로 짧게 끊어 읽기",
      "문단마다 ‘무엇을 말하는가’를 한 줄로 적기",
      "정답뿐 아니라 오답이 틀린 단어까지 표시하기",
    ],
    weeklyRule: "주 5일: 개념 2일 · 짧은 지문 2일 · 오답 복습 1일",
  },
  english: {
    label: "영어",
    shortLabel: "영",
    eyebrow: "단어와 문장 뼈대를 함께",
    promise: "단어를 외우는 데서 끝내지 않고, 긴 문장의 중심을 찾는 힘을 만듭니다.",
    method: [
      "매일 새 단어 10개보다 복습 예정 단어를 먼저 처리하기",
      "주어(S)·동사(V)를 찾은 뒤 수식어를 괄호로 묶기",
      "한 문장씩 직독직해하고 자연스러운 우리말로 다시 말하기",
    ],
    weeklyRule: "매일 단어 15분 + 구문 20분, 주 3회 듣기 15분",
  },
  math: {
    label: "수학",
    shortLabel: "수",
    eyebrow: "중학 계산부터 빈틈없이",
    promise: "공식을 통째로 외우기 전에 뜻을 이해하고, 한 줄씩 쓰는 습관을 만듭니다.",
    method: [
      "개념 예제를 손으로 다시 풀고 각 줄의 이유 말하기",
      "틀린 문제는 답 대신 틀린 첫 번째 줄을 찾아 표시하기",
      "같은 유형 3문제를 연속으로 맞힌 뒤 다음 단원으로 이동하기",
    ],
    weeklyRule: "주 6일: 개념 2일 · 기본 문제 3일 · 누적 복습 1일",
  },
};

export const TODAY_TASKS: StudyTask[] = [
  {
    id: "today-korean",
    subject: "korean",
    title: "문장 뼈대 표시하기",
    description: "짧은 독서 문장 3개에서 주어·서술어와 접속어 찾기",
    duration: 20,
    destination: "notes",
  },
  {
    id: "today-english",
    subject: "english",
    title: "오늘의 단어 복습",
    description: "예정된 단어부터 10개, 뜻을 본 뒤 기억 정도 선택하기",
    duration: 15,
    destination: "vocab",
  },
  {
    id: "today-math",
    subject: "math",
    title: "부호와 분수 계산",
    description: "핵심 규칙을 보고 기본 문제 3개를 풀이 과정과 함께 쓰기",
    duration: 25,
    destination: "notes",
  },
];

export const ROADMAPS: Record<SubjectKey, RoadmapUnit[]> = {
  korean: [
    {
      id: "ko-01",
      week: 1,
      phase: "읽기 체력",
      title: "문장 성분과 중심 문장",
      goal: "긴 문장을 주어·서술어 중심으로 끊고 핵심 내용을 한 줄로 말한다.",
      summaryKeyPoints: [
        "긴 문장에서 '주어(누가)'와 '서술어(무엇을 한다)'를 가장 먼저 괄호로 묶습니다.",
        "꾸며주는 말(수식어)을 덜어내면 아무리 길고 어려운 문장도 한눈에 파악됩니다.",
        "문단마다 가장 핵심이 되는 문장에 밑줄을 치고 한 줄로 요약하는 연습을 합니다.",
      ],
      learn: ["주어·서술어·목적어", "수식어 덜어내기", "중심 문장과 뒷받침 문장"],
      routine: ["개념 노트 10분", "문장 5개 표시 20분", "한 줄 요약 10분"],
      checkpoint: "처음 보는 문장 5개 중 4개에서 주어와 서술어를 찾으면 통과",
      noteIds: ["ko-sentence"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+윤혜정+문장성분",
    },
    {
      id: "ko-02",
      week: 2,
      phase: "읽기 체력",
      title: "접속어와 문단 관계",
      goal: "그러나·따라서·예를 들어가 앞뒤 내용을 어떻게 잇는지 설명한다.",
      summaryKeyPoints: [
        "'그러나(대조)', '따라서(인과)', '예를 들어(예시)' 접속어는 문단의 논리적 방향을 결정합니다.",
        "접속어에 표시하면서 앞문단과 뒷문단이 어떻게 연결되는지 파악합니다.",
        "글 전체가 주장-근거인지, 문제-해결인지 틀을 세우며 읽습니다.",
      ],
      learn: ["대조·인과·예시", "문단별 한 줄 요약", "글 전체 흐름"],
      routine: ["접속어 분류 10분", "짧은 문단 3개 20분", "구조 화살표 10분"],
      checkpoint: "3문단 글을 ‘주장→근거→예시’처럼 구조화하면 통과",
      noteIds: ["ko-structure"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+국어+문단관계",
    },
    {
      id: "ko-03",
      week: 3,
      phase: "읽기 체력",
      title: "어휘를 문맥으로 추론하기",
      goal: "낯선 말이 나와도 앞뒤 설명과 반대말을 이용해 뜻의 범위를 좁힌다.",
      summaryKeyPoints: [
        "모르는 단어가 나와도 당황하지 않고 앞뒤 문맥과 반대말에서 힌트를 얻습니다.",
        "지문 안에서 정의나 예시가 나온 부분에 표시해 단어의 범위를 좁힙니다.",
        "어휘 문제는 지문 속 문맥상 의미로 바꾸어 대입해 검증합니다.",
      ],
      learn: ["정의·재진술", "상위어·하위어", "문맥상 의미"],
      routine: ["기초 어휘 10분", "문맥 추론 5문항 20분", "근거 밑줄 10분"],
      checkpoint: "뜻을 몰랐던 단어 5개 중 3개 이상을 문맥 근거로 설명하면 통과",
      noteIds: ["ko-vocab-context"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+국어+어휘추론",
    },
    {
      id: "ko-04",
      week: 4,
      phase: "독서 기초",
      title: "사실·주장·근거 구분",
      goal: "필자의 주장과 이를 뒷받침하는 근거를 분리해 읽는다.",
      summaryKeyPoints: [
        "객관적 사실과 필자의 주관적 의견/주장을 명확히 분리합니다.",
        "주장을 뒷받침하는 구체적 근거 문장이 어디에 있는지 표시합니다.",
        "선지의 각 단어가 지문 속 근거 문장과 정확히 일치하는지 비교합니다.",
      ],
      learn: ["사실과 의견", "주장과 근거", "반론과 재반박"],
      routine: ["개념 10분", "인문·사회 글 1개 25분", "선지 근거 15분"],
      checkpoint: "각 선지의 판단 근거가 있는 문장을 정확히 가리키면 통과",
      noteIds: ["ko-claim"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+윤혜정+주장과근거",
    },
    {
      id: "ko-05",
      week: 5,
      phase: "독서 기초",
      title: "비교·대조와 개념 관계",
      goal: "두 대상의 공통점과 차이점을 표로 바꿔 읽는다.",
      summaryKeyPoints: [
        "두 개념이나 대상이 나오면 공통점과 차이점을 표로 메모하며 읽습니다.",
        "비교 기준(원인, 결과, 성질 등)을 찾으면 문제가 쉽게 풀립니다.",
        "A와 B의 차이점을 묻는 선지는 지문의 대조 표현에서 직결됩니다.",
      ],
      learn: ["비교 기준", "공통점·차이점", "조건에 따른 변화"],
      routine: ["관계어 확인 10분", "과학·기술 글 1개 25분", "비교표 15분"],
      checkpoint: "두 개념을 기준 3개로 비교한 표를 완성하면 통과",
      noteIds: ["ko-structure", "ko-claim"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+국어+비교대조",
    },
    {
      id: "ko-06",
      week: 6,
      phase: "독서 기초",
      title: "문제·원인·해결 구조",
      goal: "기술·사회 지문의 과정과 인과 관계를 순서도로 정리한다.",
      summaryKeyPoints: [
        "과학·기술 지문은 '원인→결과' 및 '작동 과정 순서'가 핵심입니다.",
        "순서나 과정이 나타나면 1-2-3 번호를 붙이며 읽습니다.",
        "문제 상황과 필자가 제시하는 해결책의 한계를 구분합니다.",
      ],
      learn: ["원인과 결과", "과정의 순서", "해결책의 한계"],
      routine: ["인과 표현 10분", "지문 1개 25분", "과정도 15분"],
      checkpoint: "지문을 5칸 이내 순서도로 바꾸고 조건을 빠뜨리지 않으면 통과",
      noteIds: ["ko-process"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+국어+과정지문",
    },
    {
      id: "ko-07",
      week: 7,
      phase: "문학 기초",
      title: "시: 화자·상황·정서",
      goal: "시적 화자가 처한 상황과 정서가 바뀌는 지점을 찾는다.",
      summaryKeyPoints: [
        "시적 화자가 처한 '상황(시간/공간)'과 '정서(기쁨/슬픔/체념)'를 파악합니다.",
        "시어의 긍정(+)과 부정(-) 뉘앙스를 문맥으로 구분합니다.",
        "시적 표현(비유, 상징, 역설)이 정서를 어떻게 강조하는지 봅니다.",
      ],
      learn: ["화자와 대상", "정서·태도", "심상과 표현 효과"],
      routine: ["개념어 10분", "작품 2편 25분", "근거 시어 표시 15분"],
      checkpoint: "정서를 말하고 그 근거가 되는 시어 2개를 찾으면 통과",
      noteIds: ["ko-poetry"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+윤혜정+시분석",
    },
    {
      id: "ko-08",
      week: 8,
      phase: "문학 기초",
      title: "소설: 인물·사건·서술자",
      goal: "인물 관계와 갈등, 서술자의 위치를 기준으로 장면을 읽는다.",
      summaryKeyPoints: [
        "소설은 '인물 간 갈등(내적/외적)'과 '말과 행동'이 중심입니다.",
        "인물 관계도를 머릿속이나 여백에 그리며 읽으면 장면이 이해됩니다.",
        "서술자가 작품 안에 있는지(1인칭) 밖에서 보는지(3인칭) 파악합니다.",
      ],
      learn: ["외적·내적 갈등", "서술 시점", "인물의 말과 행동"],
      routine: ["개념 10분", "짧은 장면 1개 25분", "인물 관계도 15분"],
      checkpoint: "갈등의 원인과 변화 전후를 인물 관계도로 설명하면 통과",
      noteIds: ["ko-fiction"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+국어+소설시점",
    },
    {
      id: "ko-09",
      week: 9,
      phase: "문학 기초",
      title: "고전 문학의 낯선 말 넘기",
      goal: "필수 고어와 상황 단서를 활용해 고전시가·고전소설의 큰 흐름을 잡는다.",
      summaryKeyPoints: [
        "고전시가는 자주 나오는 시어(달, 임, 님, 님향한 뜻)를 미리 외웁니다.",
        "현대어 풀이에 집착하기보다 시적 화자의 태도(충정, 자연찬미, 이별)를 잡습니다.",
        "양반의 시가와 서민의 가사를 주제별로 묶어 읽습니다.",
      ],
      learn: ["필수 고어", "관습적 소재", "현대어 풀이의 원칙"],
      routine: ["고어 10개 10분", "작품 1편 25분", "현대어 요약 15분"],
      checkpoint: "작품 상황을 인물·장소·사건 3요소로 요약하면 통과",
      noteIds: ["ko-classic"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+윤혜정+고전시가",
    },
    {
      id: "ko-10",
      week: 10,
      phase: "언어 기초",
      title: "음운·형태소·품사",
      goal: "말의 소리와 단어의 구성 단위를 구별하고 기본 품사를 판별한다.",
      summaryKeyPoints: [
        "음운(소리)과 형태소(뜻을 가진 최소 단위)를 구별합니다.",
        "체언(명사/대명사/수사)과 용언(동사/형용사)의 활용 관계를 이해합니다.",
        "단어의 품사 판별 규칙을 적용해 문법 문제를 풀어냅니다.",
      ],
      learn: ["음운과 음절", "형태소 분석", "체언·용언·수식언"],
      routine: ["개념표 15분", "분석 10문항 20분", "틀린 기준 복기 10분"],
      checkpoint: "단어 5개의 형태소와 품사를 근거와 함께 구분하면 통과",
      noteIds: ["ko-grammar"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+국어+문법기초",
    },
    {
      id: "ko-11",
      week: 11,
      phase: "문제 적용",
      title: "선지를 근거로 판정하기",
      goal: "선지의 단어를 지문 표현과 하나씩 대조해 오답 이유를 말한다.",
      summaryKeyPoints: [
        "문제 발문(무엇을 묻는가)을 먼저 읽고 지문으로 들어갑니다.",
        "지문의 표현과 선지 표현 사이의 '단어 바꿔치기' 오답 패턴을 찾아냅니다.",
        "맞힌 문제도 확실한 근거 밑줄이 있었는지 검증합니다.",
      ],
      learn: ["범위 확대", "원인·결과 뒤집기", "없는 내용 덧붙이기"],
      routine: ["오답 유형 10분", "독서 4문항 20분", "선지 해부 20분"],
      checkpoint: "틀린 선지 3개의 오류 단어를 정확히 고치면 통과",
      noteIds: ["ko-options"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+국어+발문분석",
    },
    {
      id: "ko-12",
      week: 12,
      phase: "EBS 연결",
      title: "EBS 지문을 내 노트로 바꾸기",
      goal: "강의를 듣고 끝내지 않고 지문 구조·개념·오답을 한 장에 남긴다.",
      summaryKeyPoints: [
        "EBS 수능특강/수능완성 연계 지문의 핵심 지문 구조를 익힙니다.",
        "독서 45분, 문학 30분, 선택 15분 등 자신만의 시간 배분을 점검합니다.",
        "실전 타이머 80분 훈련으로 집중력을 끝까지 유지합니다.",
      ],
      learn: ["강의 전 1차 독해", "강의 중 보충", "다음 날 재설명"],
      routine: ["지문 먼저 15분", "EBS 강의 25분", "한 장 복습 15분"],
      checkpoint: "강의 없이 지문의 구조와 핵심 개념을 2분 안에 설명하면 통과",
      noteIds: ["ko-ebs-loop"],
      youtubeUrl: "https://www.youtube.com/results?search_query=EBS+수능특강+국어",
    },
  ],
  english: [
    {
      id: "en-01",
      week: 1,
      phase: "단어 습관",
      title: "소리·뜻·예문으로 단어 익히기",
      goal: "기초 단어를 철자만 보지 않고 발음과 짧은 문장 속 의미로 기억한다.",
      learn: ["품사 표시", "대표 뜻 하나", "예문 속 쓰임"],
      routine: ["복습 예정 10분", "새 단어 10개 10분", "예문 소리 내기 10분"],
      checkpoint: "다음 날 10개 중 8개의 대표 뜻과 품사를 말하면 통과",
      noteIds: ["en-parts"],
    },
    {
      id: "en-02",
      week: 2,
      phase: "문장 뼈대",
      title: "주어와 동사 찾기",
      goal: "수식어가 긴 문장에서도 주어와 동사를 먼저 찾는다.",
      learn: ["명사 덩어리", "동사의 시제", "전치사구 괄호 치기"],
      routine: ["개념 10분", "문장 8개 표시 20분", "직독직해 10분"],
      checkpoint: "8문장 중 7문장의 S·V를 정확히 표시하면 통과",
      noteIds: ["en-sv"],
    },
    {
      id: "en-03",
      week: 3,
      phase: "문장 뼈대",
      title: "1~5형식의 핵심 자리",
      goal: "동사 뒤에 필요한 목적어와 보어 자리를 구별한다.",
      learn: ["자동사·타동사", "목적어", "주격·목적격 보어"],
      routine: ["형식표 10분", "동사별 예문 10개 20분", "해석 10분"],
      checkpoint: "문장 8개를 형식보다 ‘필요한 자리’ 기준으로 설명하면 통과",
      noteIds: ["en-patterns"],
    },
    {
      id: "en-04",
      week: 4,
      phase: "문법 기초",
      title: "시제와 수동태",
      goal: "동사의 시간과 능동·수동 관계를 해석에 반영한다.",
      learn: ["현재·과거·완료", "be + p.p.", "행위자와 대상"],
      routine: ["동사 모양 10분", "변환 10문항 20분", "오답 소리 내기 10분"],
      checkpoint: "시제·태가 다른 문장 8개 중 7개를 정확히 해석하면 통과",
      noteIds: ["en-tense-voice"],
    },
    {
      id: "en-05",
      week: 5,
      phase: "문법 기초",
      title: "to부정사·동명사·분사",
      goal: "준동사 덩어리가 문장에서 명사·형용사·부사 중 무엇처럼 쓰이는지 찾는다.",
      learn: ["to + 동사원형", "동명사", "현재·과거분사"],
      routine: ["자리 개념 10분", "괄호 표시 20분", "한 줄 해석 10분"],
      checkpoint: "준동사 덩어리 6개의 역할과 꾸미는 대상을 찾으면 통과",
      noteIds: ["en-verbals"],
    },
    {
      id: "en-06",
      week: 6,
      phase: "긴 문장",
      title: "접속사와 절의 경계",
      goal: "접속사 앞뒤의 S·V를 세어 긴 문장을 절 단위로 나눈다.",
      learn: ["명사절·형용사절·부사절", "that·if·because", "절의 시작과 끝"],
      routine: ["접속사 분류 10분", "긴 문장 6개 25분", "구조 다시 쓰기 10분"],
      checkpoint: "긴 문장 5개의 절 경계를 정확히 나누면 통과",
      noteIds: ["en-clauses"],
    },
    {
      id: "en-07",
      week: 7,
      phase: "긴 문장",
      title: "관계사와 수식 덩어리",
      goal: "관계절이 꾸미는 명사를 찾고 핵심 문장과 분리해 읽는다.",
      learn: ["관계대명사", "관계부사", "선행사"],
      routine: ["개념 10분", "선행사 화살표 20분", "직독직해 15분"],
      checkpoint: "관계절 6개 중 5개에서 선행사와 빠진 자리를 찾으면 통과",
      noteIds: ["en-relative"],
    },
    {
      id: "en-08",
      week: 8,
      phase: "독해 기초",
      title: "문단의 주제와 요지",
      goal: "반복되는 핵심어와 첫·끝 문장을 이용해 중심 내용을 찾는다.",
      learn: ["핵심어 반복", "주제문", "예시 덜어내기"],
      routine: ["단어 복습 10분", "짧은 글 2개 25분", "한글 요약 10분"],
      checkpoint: "60~100단어 글의 요지를 한 문장으로 쓰면 통과",
      noteIds: ["en-main-idea"],
    },
    {
      id: "en-09",
      week: 9,
      phase: "독해 기초",
      title: "순서·삽입의 연결 단서",
      goal: "대명사·접속어·반복어로 문장 사이의 연결을 추적한다.",
      learn: ["지시어", "논리 연결어", "같은 말 바꾸어 쓰기"],
      routine: ["연결어 10분", "문장 배열 3세트 25분", "근거 기록 10분"],
      checkpoint: "배열 순서마다 연결 근거를 한 개 이상 말하면 통과",
      noteIds: ["en-linking"],
    },
    {
      id: "en-10",
      week: 10,
      phase: "듣기 기초",
      title: "짧게 듣고 받아쓰기",
      goal: "소리 변화를 익히고 핵심 숫자·장소·의도를 놓치지 않는다.",
      learn: ["연음과 약화", "의문사", "숫자·시간 표현"],
      routine: ["1회 전체 듣기 3분", "문장 받아쓰기 12분", "대본 쉐도잉 10분"],
      checkpoint: "30초 음원의 핵심 정보를 80% 이상 받아쓰면 통과",
      noteIds: ["en-listening"],
    },
    {
      id: "en-11",
      week: 11,
      phase: "문제 적용",
      title: "빈칸과 어휘 문제의 근거",
      goal: "빈칸 주변만 보지 않고 글의 반복 논리를 이용해 답을 고른다.",
      learn: ["같은 말 재진술", "반대 전환", "보기의 범위"],
      routine: ["지문 구조 15분", "문항 3개 20분", "오답 근거 15분"],
      checkpoint: "정답의 근거와 오답의 어긋난 단어를 함께 설명하면 통과",
      noteIds: ["en-main-idea", "en-linking"],
    },
    {
      id: "en-12",
      week: 12,
      phase: "EBS 연결",
      title: "EBS 한 지문 3회전",
      goal: "첫 독해·강의 보충·다음 날 재해석으로 한 지문을 내 것으로 만든다.",
      learn: ["모르는 단어 5개 제한", "문장 구조 표시", "핵심 문장 암송"],
      routine: ["혼자 해석 15분", "EBS 강의 20분", "구조·단어 복습 15분"],
      checkpoint: "다음 날 지문을 5분 안에 다시 해석하고 요지를 말하면 통과",
      noteIds: ["en-ebs-loop"],
    },
  ],
  math: [
    {
      id: "ma-01",
      week: 1,
      phase: "중학 복구",
      title: "정수·유리수와 부호",
      goal: "음수와 분수 계산을 괄호와 부호 규칙에 맞게 한 줄씩 쓴다.",
      learn: ["절댓값", "부호가 같은·다른 수", "분수의 사칙연산"],
      routine: ["규칙 10분", "예제 3개 따라 풀기 15분", "기본 10문제 20분"],
      checkpoint: "부호·분수 혼합 계산 10문제 중 9개를 과정과 함께 맞히면 통과",
      noteIds: ["ma-number"],
    },
    {
      id: "ma-02",
      week: 2,
      phase: "중학 복구",
      title: "문자식과 지수법칙",
      goal: "같은 문자끼리 정리하고 지수법칙을 곱셈의 반복으로 설명한다.",
      learn: ["동류항", "분배법칙", "지수의 곱·몫·거듭제곱"],
      routine: ["개념 10분", "식 정리 8문제 20분", "말로 풀이 10분"],
      checkpoint: "문자식 8개 중 7개를 중간 줄을 생략하지 않고 맞히면 통과",
      noteIds: ["ma-expression", "ma-exponent"],
    },
    {
      id: "ma-03",
      week: 3,
      phase: "중학 복구",
      title: "일차방정식과 부등식",
      goal: "등식의 성질을 이용해 이항의 이유를 이해하고 해를 검산한다.",
      learn: ["등식의 성질", "일차방정식", "부등호 방향"],
      routine: ["원리 10분", "방정식 6문제 20분", "대입 검산 10분"],
      checkpoint: "괄호·분수가 있는 방정식 6문제 중 5개를 검산까지 하면 통과",
      noteIds: ["ma-linear"],
    },
    {
      id: "ma-04",
      week: 4,
      phase: "중학 복구",
      title: "좌표와 일차함수",
      goal: "x 변화에 따른 y 변화를 표·식·그래프로 서로 바꾼다.",
      learn: ["좌표", "기울기", "y절편", "두 점을 지나는 직선"],
      routine: ["좌표 찍기 10분", "그래프 5개 20분", "식↔그래프 15분"],
      checkpoint: "표·식·그래프 변환 6개 중 5개를 맞히면 통과",
      noteIds: ["ma-linear-function"],
    },
    {
      id: "ma-05",
      week: 5,
      phase: "중학 복구",
      title: "곱셈공식과 인수분해",
      goal: "전개와 인수분해가 서로 반대 과정임을 이해하고 모양을 식별한다.",
      learn: ["(a±b)²", "(a+b)(a-b)", "공통인수"],
      routine: ["공식 유도 10분", "모양 분류 10분", "기본 10문제 20분"],
      checkpoint: "전개·인수분해 혼합 10문제 중 8개를 맞히면 통과",
      noteIds: ["ma-identity", "ma-factor"],
    },
    {
      id: "ma-06",
      week: 6,
      phase: "고교 연결",
      title: "이차방정식",
      goal: "인수분해와 근의 공식을 상황에 맞게 선택하고 해를 확인한다.",
      learn: ["해와 근", "인수분해 풀이", "근의 공식", "판별식"],
      routine: ["개념 10분", "풀이법 선택 8문제 25분", "검산 10분"],
      checkpoint: "이차방정식 8개 중 7개를 알맞은 방법으로 풀면 통과",
      noteIds: ["ma-quadratic-equation"],
    },
    {
      id: "ma-07",
      week: 7,
      phase: "고교 연결",
      title: "이차함수의 그래프",
      goal: "표준형에서 꼭짓점과 축을 읽고 그래프의 이동을 설명한다.",
      learn: ["y=a(x-p)²+q", "꼭짓점·축", "최대·최소"],
      routine: ["기본 그래프 10분", "평행이동 6문제 20분", "직접 그리기 15분"],
      checkpoint: "식 5개를 꼭짓점형으로 바꾸고 그래프를 그리면 통과",
      noteIds: ["ma-quadratic-function"],
    },
    {
      id: "ma-08",
      week: 8,
      phase: "고교 연결",
      title: "방정식과 함수 연결",
      goal: "방정식의 해를 두 그래프의 교점으로 해석한다.",
      learn: ["x절편", "교점의 개수", "판별식과 그래프"],
      routine: ["개념 연결 10분", "그래프 해석 6문제 25분", "오답 그림 10분"],
      checkpoint: "식의 계산 결과와 그래프의 교점 개수를 함께 설명하면 통과",
      noteIds: ["ma-quadratic-equation", "ma-quadratic-function"],
    },
    {
      id: "ma-09",
      week: 9,
      phase: "도형 복구",
      title: "삼각형·닮음·피타고라스",
      goal: "도형 조건을 그림에 표시하고 닮음비와 길이 관계를 사용한다.",
      learn: ["삼각형 합동·닮음", "닮음비", "a²+b²=c²"],
      routine: ["조건 표시 10분", "기본 도형 6문제 25분", "보조선 복기 10분"],
      checkpoint: "도형 5문제에서 주어진 조건과 쓸 공식을 먼저 적으면 통과",
      noteIds: ["ma-geometry"],
    },
    {
      id: "ma-10",
      week: 10,
      phase: "확률 기초",
      title: "경우의 수와 확률",
      goal: "빠짐과 중복 없이 경우를 세고 전체 경우로 나누는 뜻을 이해한다.",
      learn: ["합의 법칙", "곱의 법칙", "확률=원하는 경우/전체 경우"],
      routine: ["나열 10분", "경우의 수 5문제 20분", "확률 5문제 20분"],
      checkpoint: "작은 경우를 직접 나열해 공식 결과를 확인하면 통과",
      noteIds: ["ma-counting"],
    },
    {
      id: "ma-11",
      week: 11,
      phase: "문제 적용",
      title: "조건을 식으로 번역하기",
      goal: "문장제의 조건을 변수·식·그림으로 바꾼 뒤 계산한다.",
      learn: ["미지수 정하기", "단위 맞추기", "조건별 식 세우기"],
      routine: ["조건 표시 10분", "문장제 5문제 25분", "검산·단위 10분"],
      checkpoint: "계산 전 미지수와 식을 올바르게 세운 문제가 4개 이상이면 통과",
      noteIds: ["ma-translation"],
    },
    {
      id: "ma-12",
      week: 12,
      phase: "EBS 연결",
      title: "개념 강의와 유형 3문제",
      goal: "EBS 개념 강의 한 구간을 듣고 대표·유사·변형 문제로 반복한다.",
      learn: ["강의 전 예제", "멈춤 후 직접 계산", "오답 첫 줄 기록"],
      routine: ["예습 10분", "EBS 강의 25분", "유형 3문제 20분"],
      checkpoint: "강의 없이 유사 문제 3개를 연속으로 맞히면 통과",
      noteIds: ["ma-ebs-loop"],
    },
  ],
};

export const CORE_NOTES: CoreNote[] = [
  { id: "ko-sentence", subject: "korean", category: "문장", title: "문장 뼈대 찾기", oneLine: "수식어를 잠시 덜고 누가/무엇이 + 어찌한다를 먼저 찾습니다.", essentials: ["주어: 동작·상태의 주체", "서술어: 주어의 동작·상태", "관형어·부사어는 뼈대를 꾸미는 말"], mistake: "긴 수식어 안의 동사를 문장의 중심 동사로 착각하지 않기", microPractice: "오늘 읽은 문장 하나에서 수식어를 괄호로 묶어 보세요." },
  { id: "ko-structure", subject: "korean", category: "독서", title: "문단 구조 신호", oneLine: "접속어는 다음 문단의 역할을 미리 알려 주는 표지판입니다.", essentials: ["그러나·반면: 대조/전환", "따라서·그러므로: 결과/결론", "예를 들어: 앞 개념의 구체화"], mistake: "접속어에만 표시하고 실제로 무엇과 무엇이 연결되는지 놓치지 않기", microPractice: "세 문단 글을 주장→근거→예시처럼 화살표로 적어 보세요." },
  { id: "ko-vocab-context", subject: "korean", category: "독서", title: "문맥 어휘 추론", oneLine: "정의·재진술·반대 표현을 찾아 뜻의 범위를 좁힙니다.", essentials: ["‘즉·다시 말해’ 뒤는 재진술", "쉼표 뒤 설명은 정의일 수 있음", "반대로 이어지면 반대 의미 확인"], mistake: "평소 아는 뜻 하나를 문맥에 억지로 넣지 않기", microPractice: "낯선 말 앞뒤 2문장만 읽고 가능한 뜻을 한 문장으로 적어 보세요." },
  { id: "ko-claim", subject: "korean", category: "독서", title: "주장과 근거", oneLine: "필자가 믿는 내용과 그렇게 믿는 이유를 분리합니다.", essentials: ["주장: 판단·제안이 담긴 문장", "근거: 사례·자료·원리", "반론 뒤 재반박이 최종 주장일 수 있음"], mistake: "흥미로운 사례를 글의 주장으로 고르지 않기", microPractice: "지문에서 ‘필자는 ___라고 본다. 왜냐하면 ___’을 완성하세요." },
  { id: "ko-process", subject: "korean", category: "독서", title: "과정·인과 읽기", oneLine: "조건→작동→결과를 번호로 바꾸면 기술 지문이 짧아집니다.", essentials: ["원인과 단순한 시간 순서 구별", "조건이 바뀌면 결과도 다시 확인", "과정마다 주체가 무엇인지 표시"], mistake: "A 다음 B가 나왔다고 언제나 A가 B의 원인이라고 단정하지 않기", microPractice: "과정 설명 한 문단을 ①→②→③으로 바꾸세요." },
  { id: "ko-poetry", subject: "korean", category: "문학", title: "시를 읽는 세 질문", oneLine: "누가, 어떤 상황에서, 어떤 태도를 보이는지 찾습니다.", essentials: ["화자는 작가와 같지 않음", "정서는 시어와 이미지에서 확인", "전환어·장면 변화가 태도 변화 지점"], mistake: "근거 시어 없이 ‘슬프다’처럼 감정만 추측하지 않기", microPractice: "화자·상황·정서를 각각 한 줄로 적고 근거 시어에 밑줄 치세요." },
  { id: "ko-fiction", subject: "korean", category: "문학", title: "소설 장면 읽기", oneLine: "인물의 말·행동과 갈등 변화를 따라갑니다.", essentials: ["내적 갈등: 한 인물 마음속 충돌", "외적 갈등: 인물-인물/사회/환경", "서술자는 정보의 범위를 결정"], mistake: "서술자의 판단을 등장인물의 생각으로 바꾸어 읽지 않기", microPractice: "장면 전후로 인물의 목표가 어떻게 달라졌는지 적어 보세요." },
  { id: "ko-classic", subject: "korean", category: "문학", title: "고전 문학 첫 접근", oneLine: "모든 단어를 번역하기보다 인물·장소·사건부터 잡습니다.", essentials: ["필수 고어는 작품마다 반복", "자연물은 정서·가치의 매개", "고전소설은 신분·명분·인과에 주목"], mistake: "한 단어를 몰라 문장 전체 읽기를 멈추지 않기", microPractice: "낯선 고어는 동그라미만 치고 장면을 현대어 한 줄로 요약하세요." },
  { id: "ko-grammar", subject: "korean", category: "언어", title: "말의 단위", oneLine: "음운은 소리, 형태소는 뜻, 품사는 쓰임의 갈래입니다.", essentials: ["음운: 뜻을 구별하는 가장 작은 소리", "형태소: 뜻을 가진 가장 작은 말의 단위", "품사: 형태·기능·의미로 분류"], mistake: "글자 수와 음운 수, 어절 수와 형태소 수를 같다고 보지 않기", microPractice: "‘먹었다’를 먹-/-었-/-다로 나누고 각 기능을 말해 보세요." },
  { id: "ko-options", subject: "korean", category: "문제", title: "오답 선지 4유형", oneLine: "선지 전체가 아니라 지문과 어긋난 한 단어를 찾습니다.", essentials: ["범위 확대·축소", "원인과 결과 뒤집기", "주체 바꾸기", "지문에 없는 판단 추가"], mistake: "익숙하거나 그럴듯하다는 이유로 선지를 고르지 않기", microPractice: "틀린 선지에서 딱 한 부분을 고쳐 참인 문장으로 만드세요." },
  { id: "ko-ebs-loop", subject: "korean", category: "EBS", title: "EBS 3회전", oneLine: "먼저 읽고, 강의로 보충하고, 다음 날 스스로 설명합니다.", essentials: ["강의 전 지문 구조 표시", "강의 중 새 정보만 보충", "24시간 안에 무자료 복습"], mistake: "강의 필기를 예쁘게 베끼는 것으로 복습을 끝내지 않기", microPractice: "강의 후 노트를 덮고 핵심을 60초 동안 설명해 보세요." },
  { id: "en-parts", subject: "english", category: "기초", title: "품사와 문장 자리", oneLine: "단어 뜻과 함께 명사·동사·형용사·부사 중 역할을 봅니다.", essentials: ["명사: 주어·목적어·보어 자리", "형용사: 명사 설명", "부사: 명사 외의 말이나 문장 전체 설명"], mistake: "같은 단어가 문장마다 다른 품사로 쓰일 수 있음을 놓치지 않기", microPractice: "오늘 단어 5개 옆에 품사와 예문 속 자리를 표시하세요." },
  { id: "en-sv", subject: "english", category: "구문", title: "S·V 먼저 찾기", oneLine: "전치사구와 수식어를 괄호로 묶고 핵심 주어·동사를 남깁니다.", essentials: ["동사 모양은 시제·조동사와 함께 확인", "전치사+명사는 대개 수식 덩어리", "절마다 S·V 한 쌍"], formula: "[수식어] + S + V + (필요한 자리)", mistake: "to부정사·분사를 본동사로 세지 않기", microPractice: "긴 문장 하나에 S에는 밑줄, V에는 네모를 표시하세요." },
  { id: "en-patterns", subject: "english", category: "구문", title: "동사 뒤 필수 자리", oneLine: "형식 번호보다 동사가 무엇을 더 요구하는지 확인합니다.", essentials: ["1형식: S+V", "2형식: S+V+C", "3형식: S+V+O", "4형식: S+V+O+O", "5형식: S+V+O+C"], mistake: "전치사 뒤 명사를 동사의 직접 목적어로 착각하지 않기", microPractice: "동사 뒤 필수 성분까지만 남겨 문장을 짧게 다시 쓰세요." },
  { id: "en-tense-voice", subject: "english", category: "문법", title: "시제와 수동태", oneLine: "동사의 시간과 행동의 방향을 함께 봅니다.", essentials: ["완료: have + p.p.", "진행: be + -ing", "수동: be + p.p."], formula: "수동태 = be동사(시제 담당) + p.p.(수동 의미)", mistake: "p.p.만 보고 모두 수동태라고 판단하지 않기", microPractice: "문장의 동사를 시간·능동/수동 두 축으로 설명하세요." },
  { id: "en-verbals", subject: "english", category: "문법", title: "준동사 세 가지", oneLine: "동사에서 왔지만 문장에서는 다른 품사의 자리를 맡습니다.", essentials: ["to부정사: 명사·형용사·부사 역할", "동명사: 명사 역할", "분사: 형용사 역할"], mistake: "준동사에 시제를 맡겨 문장의 본동사로 읽지 않기", microPractice: "준동사 덩어리를 괄호로 묶고 문장 속 역할을 적으세요." },
  { id: "en-clauses", subject: "english", category: "구문", title: "절의 경계", oneLine: "접속사는 새로운 S·V 묶음이 시작된다는 신호입니다.", essentials: ["명사절: 문장의 명사 자리", "형용사절: 앞 명사 수식", "부사절: 때·이유·조건·양보"], formula: "접속사 수를 확인하고 각 절의 S·V를 짝짓기", mistake: "접속사 없이 동사처럼 보이는 준동사를 절로 세지 않기", microPractice: "긴 문장을 / 로 나누고 절마다 S·V 번호를 붙이세요." },
  { id: "en-relative", subject: "english", category: "구문", title: "관계사", oneLine: "관계절은 앞 명사(선행사)를 설명하는 형용사 덩어리입니다.", essentials: ["who·which·that 뒤에는 한 자리가 비어 있음", "where·when 뒤에는 완전한 문장", "관계절 전체가 선행사를 수식"], mistake: "관계사절 내부 해석만 하다가 선행사와의 연결을 놓치지 않기", microPractice: "관계사에서 선행사로 화살표를 긋고 절 전체를 괄호 치세요." },
  { id: "en-main-idea", subject: "english", category: "독해", title: "주제 찾기", oneLine: "반복되는 핵심어와 필자의 판단이 만나는 문장을 찾습니다.", essentials: ["예시는 핵심을 설명하는 재료", "but·however 뒤 전환 주목", "첫 문장과 끝 문장의 연결 확인"], mistake: "지문 일부의 흥미로운 소재를 전체 주제로 확대하지 않기", microPractice: "글을 ‘필자는 ___에 대해 ___라고 말한다’로 요약하세요." },
  { id: "en-linking", subject: "english", category: "독해", title: "문장 연결 단서", oneLine: "지시어·반복어·논리어가 앞뒤 문장을 이어 줍니다.", essentials: ["this/these가 가리키는 내용", "동의어·상위어 반복", "therefore/for example/however의 관계"], mistake: "접속어 뜻만 외우고 실제 앞뒤 내용의 관계를 확인하지 않기", microPractice: "대명사 하나가 가리키는 앞 문장 내용을 직접 적으세요." },
  { id: "en-listening", subject: "english", category: "듣기", title: "듣기 3단계", oneLine: "전체 의미→빈칸 받아쓰기→대본 쉐도잉 순으로 반복합니다.", essentials: ["첫 회에는 멈추지 않고 목적 파악", "둘째 회에는 놓친 소리 확인", "마지막에는 같은 속도로 따라 말하기"], mistake: "대본을 먼저 읽은 뒤 들었다고 착각하지 않기", microPractice: "30초 음원을 듣고 숫자·장소·의도를 먼저 적으세요." },
  { id: "en-ebs-loop", subject: "english", category: "EBS", title: "EBS 지문 3회전", oneLine: "혼자 해석한 흔적 위에 강의에서 얻은 것만 더합니다.", essentials: ["1회: S·V와 모르는 단어 표시", "2회: 강의로 구조 수정", "3회: 다음 날 무자료 해석"], mistake: "모든 단어 뜻을 베껴 적느라 글의 요지를 놓치지 않기", microPractice: "다음 날 핵심 문장을 구조대로 다시 해석하세요." },
  { id: "ma-number", subject: "math", category: "중학 기초", title: "부호와 분수", oneLine: "부호를 먼저 결정하고 절댓값을 계산합니다.", essentials: ["같은 부호의 곱·몫은 +", "다른 부호의 곱·몫은 -", "분수 덧셈·뺄셈은 공통분모부터"], formula: "(-a)×(-b)=ab,  (-a)×b=-ab", mistake: "빼기 기호와 음수 부호를 같은 것으로 보고 괄호를 생략하지 않기", microPractice: "부호만 먼저 적은 뒤 계산하는 문제 3개를 풀어 보세요." },
  { id: "ma-expression", subject: "math", category: "중학 기초", title: "문자식 정리", oneLine: "동류항끼리만 계수를 계산하고 문자는 그대로 둡니다.", essentials: ["동류항: 문자와 지수가 같음", "괄호 앞 수는 모든 항에 분배", "나눗셈은 분수꼴로 먼저 쓰기"], formula: "a(b+c)=ab+ac", mistake: "2x+3을 5x로 합치지 않기", microPractice: "식을 항별로 색을 달리해 동류항끼리 묶어 보세요." },
  { id: "ma-exponent", subject: "math", category: "중학 기초", title: "지수법칙", oneLine: "밑이 같은 곱셈은 지수를 더하고, 거듭제곱은 지수를 곱합니다.", essentials: ["aᵐaⁿ=aᵐ⁺ⁿ", "aᵐ/aⁿ=aᵐ⁻ⁿ (a≠0)", "(aᵐ)ⁿ=aᵐⁿ"], formula: "a⁰=1 (a≠0),  a⁻ⁿ=1/aⁿ", mistake: "(a+b)²을 a²+b²으로 계산하지 않기", microPractice: "각 공식을 같은 수의 반복 곱셈으로 한 번 확인하세요." },
  { id: "ma-linear", subject: "math", category: "방정식", title: "일차방정식", oneLine: "양변에 같은 연산을 해도 등식은 유지됩니다.", essentials: ["괄호 풀기", "분모 없애기", "동류항 정리", "대입 검산"], formula: "ax+b=c → x=(c-b)/a (a≠0)", mistake: "이항할 때 부호만 외우고 항 전체가 이동한다는 뜻을 잊지 않기", microPractice: "푼 해를 원래 식 양변에 대입해 같은 값인지 확인하세요." },
  { id: "ma-linear-function", subject: "math", category: "함수", title: "일차함수", oneLine: "기울기는 x가 1 늘 때 y가 얼마나 변하는지 뜻합니다.", essentials: ["기울기=(y의 변화량)/(x의 변화량)", "y절편은 x=0일 때 y", "평행한 직선은 기울기가 같음"], formula: "y=mx+n,  m=(y₂-y₁)/(x₂-x₁)", mistake: "두 점의 순서를 분자와 분모에서 다르게 잡지 않기", microPractice: "두 점을 찍고 변화량 삼각형을 그려 기울기를 구하세요." },
  { id: "ma-identity", subject: "math", category: "식", title: "곱셈공식", oneLine: "넓이 그림이나 분배법칙으로 직접 전개해 기억합니다.", essentials: ["(a+b)²=a²+2ab+b²", "(a-b)²=a²-2ab+b²", "(a+b)(a-b)=a²-b²"], formula: "(x+a)(x+b)=x²+(a+b)x+ab", mistake: "가운데 항 2ab의 부호와 계수를 빠뜨리지 않기", microPractice: "공식 하나를 분배법칙으로 직접 전개하세요." },
  { id: "ma-factor", subject: "math", category: "식", title: "인수분해", oneLine: "전개의 반대 과정으로, 먼저 공통인수를 찾습니다.", essentials: ["공통인수 묶기", "완전제곱식 모양", "합과 곱으로 두 수 찾기"], formula: "x²+(a+b)x+ab=(x+a)(x+b)", mistake: "인수분해 뒤 다시 전개해 원래 식인지 확인하지 않는 습관", microPractice: "인수분해한 식을 바로 전개해 검산하세요." },
  { id: "ma-quadratic-equation", subject: "math", category: "방정식", title: "이차방정식", oneLine: "0=꼴로 만든 뒤 인수분해 가능 여부를 먼저 봅니다.", essentials: ["AB=0이면 A=0 또는 B=0", "인수분해가 안 되면 근의 공식", "판별식으로 실근 개수 확인"], formula: "x=(-b±√(b²-4ac))/(2a),  D=b²-4ac", mistake: "우변이 0이 아닌 상태에서 각 인수를 0으로 놓지 않기", microPractice: "풀이 전에 인수분해/근의 공식 중 선택 이유를 한 단어로 적으세요." },
  { id: "ma-quadratic-function", subject: "math", category: "함수", title: "이차함수", oneLine: "꼭짓점형에서 축과 이동을 바로 읽습니다.", essentials: ["꼭짓점 (p,q)", "축 x=p", "a>0 아래로 볼록, a<0 위로 볼록"], formula: "y=a(x-p)²+q", mistake: "x-p의 부호와 꼭짓점 x좌표의 부호를 반대로 읽지 않기", microPractice: "식에서 꼭짓점·축·열리는 방향을 읽고 스케치하세요." },
  { id: "ma-geometry", subject: "math", category: "도형", title: "닮음과 피타고라스", oneLine: "같은 위치의 변을 대응시킨 뒤 비를 세웁니다.", essentials: ["닮음비가 k면 넓이비는 k²", "직각삼각형에서 빗변이 c", "조건을 그림에 직접 표시"], formula: "a²+b²=c²", mistake: "가장 긴 변이 아니라 직각의 맞은편이 빗변임을 놓치지 않기", microPractice: "직각·같은 각·같은 길이를 그림에 모두 표시한 뒤 계산하세요." },
  { id: "ma-counting", subject: "math", category: "확률", title: "경우의 수와 확률", oneLine: "작은 경우를 먼저 나열해 빠짐과 중복을 확인합니다.", essentials: ["동시에 선택: 곱의 법칙", "서로 겹치지 않는 선택: 합의 법칙", "확률=원하는 경우/전체 경우"], formula: "P(A)=n(A)/n(S),  0≤P(A)≤1", mistake: "순서를 구분하는 경우와 구분하지 않는 경우를 섞지 않기", microPractice: "공식 전에 표나 나무 그림으로 모든 경우를 적어 보세요." },
  { id: "ma-translation", subject: "math", category: "문제", title: "문장을 식으로", oneLine: "무엇을 x로 둘지와 단위를 먼저 정합니다.", essentials: ["미지수 정의", "같은 단위로 통일", "문장 조건마다 식 하나", "답이 상황에 맞는지 확인"], mistake: "식은 맞아도 답의 단위·범위를 쓰지 않는 실수", microPractice: "계산 전 ‘x는 ___이다’와 단위를 한 줄로 쓰세요." },
  { id: "ma-ebs-loop", subject: "math", category: "EBS", title: "EBS 개념 3문제", oneLine: "강의 한 구간마다 대표·유사·변형 문제를 직접 풉니다.", essentials: ["강의 전 예제 시도", "계산 장면에서 멈추고 직접 풀기", "오답은 틀린 첫 줄 기록"], mistake: "강사의 풀이를 이해한 느낌을 혼자 풀 수 있는 상태로 착각하지 않기", microPractice: "강의를 닫고 같은 유형 3문제를 연속으로 풀어 보세요." },
];

export const EBS_LINKS = [
  {
    id: "ko-ebs-course",
    subject: "korean" as const,
    title: "EBSi 고등예비과정 공통국어",
    description: "문장 읽기와 핵심 독해 개념을 처음부터 다시 잡는 공식 입문 강좌입니다.",
    href: "https://www.ebsi.co.kr/ebs/pot/potg/retrieveCourseDetailNw.ebs?bookId=LB00000005517",
    type: "ebsi" as const,
  },
  {
    id: "ko-yt-navi",
    subject: "korean" as const,
    title: "YouTube 윤혜정의 개념의 나비효과",
    description: "전국 수험생 독해 필독서! 국어 영역 핵심 개념 무료 유튜브 강좌입니다.",
    href: "https://www.youtube.com/results?search_query=EBS+윤혜정+개념의+나비효과",
    type: "youtube" as const,
  },
  {
    id: "en-ebs-course",
    subject: "english" as const,
    title: "EBSi 고등예비과정 공통영어",
    description: "기초 어휘와 구문 독해 감각을 함께 시작하는 공식 입문 강좌입니다.",
    href: "https://www.ebsi.co.kr/ebs/pot/potg/retrieveCourseDetailNw.ebs?bookId=LB00000005455",
    type: "ebsi" as const,
  },
  {
    id: "en-yt-joo",
    subject: "english" as const,
    title: "YouTube 주혜연의 해석공식 / 수능특강",
    description: "문장 뼈대 잡기와 수능 영어 직독직해 구문 해석 유튜브 특강입니다.",
    href: "https://www.youtube.com/results?search_query=EBS+주혜연+해석공식",
    type: "youtube" as const,
  },
  {
    id: "ma-ebs-course",
    subject: "math" as const,
    title: "EBSi 고등예비과정 공통수학",
    description: "중학 계산 복습부터 공통수학 핵심 개념까지 이어 주는 공식 입문 과정입니다.",
    href: "https://www.ebsi.co.kr/ebs/pot/potg/retrieveCourseDetailNw.ebs?bookId=LB00000005472",
    type: "ebsi" as const,
  },
  {
    id: "ma-yt-50day",
    subject: "math" as const,
    title: "YouTube EBS 50일 수학 (정승제/정종영)",
    description: "노베이스 필수! 초·중등 수학부터 고등 수학까지 50일 완성 무료 유튜브 강의입니다.",
    href: "https://www.youtube.com/results?search_query=EBS+50일+수학",
    type: "youtube" as const,
  },
];
