export type VocabTag = "reading" | "listening" | "writing" | "logic";

/**
 * 빈도 순서로 나눈 단계. 1은 중학~고1 기초 고빈도,
 * 2·3은 뒤에 이어 붙일 자리라 기존 단어를 다시 정렬할 필요가 없다.
 */
export type VocabStage = 1 | 2 | 3;

export type VocabWordEntry = {
  id: string;
  word: string;
  meaning: string;
  example: string;
  exampleTranslation: string;
  tags: readonly VocabTag[];
  stage: VocabStage;
};

export const VOCAB_WORDS: readonly VocabWordEntry[] = [
  { id: "assume", word: "assume", meaning: "가정하다, 추정하다", example: "Do not assume the writer agrees with every example.", exampleTranslation: "필자의 모든 예시에 동의한다고 가정하지 마라.", tags: ["reading", "logic"], stage: 1 },
  { id: "require", word: "require", meaning: "요구하다, 필요로 하다", example: "This question requires careful reading of the final sentence.", exampleTranslation: "이 문제는 마지막 문장을 주의 깊게 읽을 것을 요구한다.", tags: ["reading"], stage: 1 },
  { id: "evidence", word: "evidence", meaning: "근거, 증거", example: "You need evidence to support your answer.", exampleTranslation: "답을 뒷받침할 근거가 필요하다.", tags: ["reading", "writing"], stage: 1 },
  { id: "suggest", word: "suggest", meaning: "시사하다, 암시하다, 제안하다", example: "The data suggest a clear change in behavior.", exampleTranslation: "그 자료는 행동의 뚜렷한 변화를 시사한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "likely", word: "likely", meaning: "~할 것 같은, 가능성 있는", example: "The most likely answer is not always the longest one.", exampleTranslation: "가장 가능성 있는 답이 항상 가장 긴 것은 아니다.", tags: ["reading"], stage: 1 },
  { id: "increase", word: "increase", meaning: "증가하다, 높이다", example: "Regular review can increase memory retention.", exampleTranslation: "규칙적인 복습은 기억 유지력을 높일 수 있다.", tags: ["logic"], stage: 1 },
  { id: "reduce", word: "reduce", meaning: "줄이다, 감소시키다", example: "A simple routine reduces careless mistakes.", exampleTranslation: "단순한 루틴은 부주의한 실수를 줄인다.", tags: ["logic"], stage: 1 },
  { id: "compare", word: "compare", meaning: "비교하다", example: "Compare the two passages before choosing an answer.", exampleTranslation: "답을 고르기 전에 두 지문을 비교하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "contrast", word: "contrast", meaning: "대조하다, 대조", example: "The author contrasts habit with true understanding.", exampleTranslation: "저자는 습관과 진정한 이해를 대조한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "focus", word: "focus", meaning: "집중하다, 초점", example: "Focus on the main claim before reading details.", exampleTranslation: "세부를 읽기 전에 핵심 주장에 집중하라.", tags: ["reading"], stage: 1 },
  { id: "include", word: "include", meaning: "포함하다", example: "The summary should include only essential points.", exampleTranslation: "요약에는 핵심 포인트만 포함되어야 한다.", tags: ["writing"], stage: 1 },
  { id: "essential", word: "essential", meaning: "필수적인, 본질적인", example: "Understanding grammar is essential for reading long sentences.", exampleTranslation: "문법 이해는 긴 문장을 읽는 데 필수적이다.", tags: ["reading"], stage: 1 },
  { id: "concept", word: "concept", meaning: "개념", example: "Master one concept before moving to the next.", exampleTranslation: "다음으로 넘어가기 전에 한 개념을 마스터하라.", tags: ["logic"], stage: 1 },
  { id: "process", word: "process", meaning: "과정, 처리하다", example: "Learning is a gradual process of building confidence.", exampleTranslation: "학습은 자신감을 쌓아가는 점진적인 과정이다.", tags: ["logic"], stage: 1 },
  { id: "result", word: "result", meaning: "결과, ~로 끝나다", example: "Clear practice results in stable scores.", exampleTranslation: "명확한 연습은 안정적인 점수로 이어진다.", tags: ["logic"], stage: 1 },
  { id: "simple", word: "simple", meaning: "단순한, 명쾌한", example: "A simple schedule is easier to continue.", exampleTranslation: "단순한 계획표가 계속하기 더 쉽다.", tags: ["logic"], stage: 1 },
  { id: "context", word: "context", meaning: "맥락, 문맥", example: "The sentence makes sense only in its full context.", exampleTranslation: "그 문장은 전체 맥락 속에서만 의미가 통한다.", tags: ["reading"], stage: 1 },
  { id: "infer", word: "infer", meaning: "추론하다", example: "You can infer the writer's attitude from the final paragraph.", exampleTranslation: "마지막 문단에서 필자의 태도를 추론할 수 있다.", tags: ["reading", "logic"], stage: 1 },
  { id: "derive", word: "derive", meaning: "끌어내다, 유래하다", example: "We can derive the main idea from the first paragraph.", exampleTranslation: "첫 문단에서 중심 생각을 끌어낼 수 있다.", tags: ["reading", "logic"], stage: 1 },
  { id: "distinct", word: "distinct", meaning: "뚜렷한, 별개의", example: "The two solutions have distinct advantages.", exampleTranslation: "두 해결책은 뚜렷이 다른 장점을 가진다.", tags: ["logic"], stage: 1 },
  { id: "factor", word: "factor", meaning: "요인, 요소", example: "Sleep is a major factor in steady study habits.", exampleTranslation: "수면은 꾸준한 공부 습관의 주요 요인이다.", tags: ["logic"], stage: 1 },
  { id: "relevant", word: "relevant", meaning: "관련된, 적절한", example: "Choose only the evidence relevant to the claim.", exampleTranslation: "주장과 관련 있는 근거만 고르라.", tags: ["reading", "logic"], stage: 1 },
  { id: "valid", word: "valid", meaning: "타당한, 유효한", example: "A valid answer must match the passage exactly.", exampleTranslation: "타당한 답은 지문과 정확히 일치해야 한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "conclude", word: "conclude", meaning: "결론짓다", example: "Do not conclude too early from one sentence.", exampleTranslation: "한 문장만 보고 너무 일찍 결론짓지 마라.", tags: ["reading", "logic"], stage: 1 },
  { id: "reflect", word: "reflect", meaning: "반영하다, 숙고하다", example: "Your notes should reflect the text structure.", exampleTranslation: "네 노트는 글의 구조를 반영해야 한다.", tags: ["writing", "reading"], stage: 1 },
  { id: "evaluate", word: "evaluate", meaning: "평가하다, 가치를 가늠하다", example: "Students must evaluate the logical soundness of the argument.", exampleTranslation: "학생들은 주장의 논리적 타당성을 평가해야 한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "illustrate", word: "illustrate", meaning: "설명하다, 예시를 들다", example: "The chart illustrates how energy consumption changes over time.", exampleTranslation: "도표는 시간에 따른 에너지 소비 변화를 보여준다.", tags: ["reading"], stage: 1 },
  { id: "emphasize", word: "emphasize", meaning: "강조하다", example: "The speaker emphasized the importance of daily practice.", exampleTranslation: "강연자는 매일 하는 연습의 중요성을 강조했다.", tags: ["listening", "reading"], stage: 1 },
  { id: "fundamental", word: "fundamental", meaning: "근본적인, 핵심적인", example: "Grammar rules provide the fundamental structure of language.", exampleTranslation: "문법 규칙은 언어의 근본적인 구조를 제공한다.", tags: ["reading"], stage: 1 },
  { id: "perspective", word: "perspective", meaning: "관점, 시각", example: "Try to understand the problem from a different perspective.", exampleTranslation: "다른 관점에서 문제를 이해하려고 시도하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "consequence", word: "consequence", meaning: "결과, 중요성", example: "Every decision in reading has a logical consequence.", exampleTranslation: "독해에서의 모든 판단에는 논리적 결과가 따른다.", tags: ["reading", "logic"], stage: 1 },
  { id: "inevitable", word: "inevitable", meaning: "피할 수 없는, 불가피한", example: "Some mistakes are inevitable during the initial learning phase.", exampleTranslation: "초기 학습 단계에서 몇몇 실수는 피할 수 없다.", tags: ["logic"], stage: 1 },
  { id: "hypothesis", word: "hypothesis", meaning: "가설", example: "Scientists test their hypothesis through repeated experiments.", exampleTranslation: "과학자들은 반복된 실험을 통해 가설을 검증한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "phenomenon", word: "phenomenon", meaning: "현상", example: "Social media is a modern cultural phenomenon.", exampleTranslation: "소셜 미디어는 현대의 문화적 현상이다.", tags: ["reading"], stage: 1 },
  { id: "consistent", word: "consistent", meaning: "일관된, 지속적인", example: "Consistent study brings better results than cramming.", exampleTranslation: "벼락치기보다 일관된 공부가 더 나은 결과를 가져온다.", tags: ["logic"], stage: 1 },
  { id: "significant", word: "significant", meaning: "중요한, 상당한", example: "There is a significant difference between reading and understanding.", exampleTranslation: "그냥 읽는 것과 이해하는 것 사이에는 상당한 차이가 있다.", tags: ["reading", "logic"], stage: 1 },
  { id: "alternative", word: "alternative", meaning: "대안, 대체 가능한", example: "The author proposes an alternative explanation for the trend.", exampleTranslation: "저자는 그 경향에 대해 대안적인 설명을 제시한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "attribute", word: "attribute", meaning: "~의 탓으로 돌리다, 특성", example: "He attributes his success to steady practice.", exampleTranslation: "그는 자신의 성공을 꾸준한 연습 덕분으로 돌린다.", tags: ["reading"], stage: 1 },
  { id: "capacity", word: "capacity", meaning: "수용 능력, 용량", example: "Human memory capacity expands through structured association.", exampleTranslation: "인간의 기억 용량은 구조화된 연상을 통해 확장된다.", tags: ["reading"], stage: 1 },
  { id: "compromise", word: "compromise", meaning: "타협하다, 손상시키다", example: "Never compromise accuracy for speed in early stages.", exampleTranslation: "초기 단계에서 속도를 위해 정확도를 타협하지 마라.", tags: ["logic"], stage: 1 },
  { id: "crucial", word: "crucial", meaning: "중요한, 결정적인", example: "Identifying the main subject is crucial in reading comprehension.", exampleTranslation: "주요 주제를 파악하는 것은 독해에서 결정적이다.", tags: ["reading"], stage: 1 },
  { id: "decline", word: "decline", meaning: "감소하다, 거절하다", example: "Test anxiety tends to decline as preparation increases.", exampleTranslation: "시험 불안은 준비가 늘어남에 따라 줄어드는 경향이 있다.", tags: ["logic"], stage: 1 },
  { id: "demonstrate", word: "demonstrate", meaning: "증명하다, 시연하다", example: "The experiment demonstrates how memory works.", exampleTranslation: "그 실험은 기억이 어떻게 작동하는지 증명한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "determine", word: "determine", meaning: "결정하다, 알아내다", example: "Context helps determine the exact meaning of a word.", exampleTranslation: "문맥은 단어의 정확한 의미를 결정하는 데 도움을 준다.", tags: ["reading"], stage: 1 },
  { id: "dimension", word: "dimension", meaning: "차원, 관점", example: "Literature adds a emotional dimension to language study.", exampleTranslation: "문학은 언어 공부에 감정적 차원을 더해준다.", tags: ["reading"], stage: 1 },
  { id: "dominate", word: "dominate", meaning: "지배하다, 우세를 점하다", example: "One central topic dominates the entire paragraph.", exampleTranslation: "하나의 중심 주제가 문단 전체를 지배한다.", tags: ["reading"], stage: 1 },
  { id: "efficient", word: "efficient", meaning: "효율적인", example: "SRS vocabulary review is an efficient method.", exampleTranslation: "SRS 단어 복습은 효율적인 방법이다.", tags: ["logic"], stage: 1 },
  { id: "eliminate", word: "eliminate", meaning: "제거하다, 오답을 지우다", example: "Eliminate choices that contradict the passage.", exampleTranslation: "지문과 모순되는 선지를 제거하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "encounter", word: "encounter", meaning: "우연히 마주치다, 직면하다", example: "When you encounter a new word, guess its meaning first.", exampleTranslation: "새 단어를 마주쳤을 때, 먼저 의미를 추측해 보라.", tags: ["reading"], stage: 1 },
  { id: "enhance", word: "enhance", meaning: "향상시키다, 강화하다", example: "Reading daily will enhance your vocabulary skills.", exampleTranslation: "매일 읽는 것은 당신의 어휘력을 향상시킬 것이다.", tags: ["reading"], stage: 1 },
  { id: "establish", word: "establish", meaning: "설립하다, 확립하다", example: "Establish a fixed study environment for deep focus.", exampleTranslation: "깊은 집중을 위해 고정된 공부 환경을 확립하라.", tags: ["logic"], stage: 1 },
  { id: "exaggerate", word: "exaggerate", meaning: "과장하다", example: "Do not exaggerate small details when summarizing.", exampleTranslation: "요약할 때 사소한 세부를 과장하지 마라.", tags: ["writing", "reading"], stage: 1 },
  { id: "explicit", word: "explicit", meaning: "명시적인, 뚜렷한", example: "The paragraph gives an explicit warning about errors.", exampleTranslation: "그 문단은 오류에 대해 명시적인 경고를 준다.", tags: ["reading", "logic"], stage: 1 },
  { id: "implicit", word: "implicit", meaning: "암묵적인, 내포된", example: "Identify the implicit assumption behind the author's argument.", exampleTranslation: "저자의 주장 뒤에 숨은 암묵적 가설을 파악하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "imply", word: "imply", meaning: "암시하다, 넌지시 말하다", example: "The passage implies that technology has dual effects.", exampleTranslation: "지문은 기술이 두 가지 효과를 지님을 암시한다.", tags: ["reading"], stage: 1 },
  { id: "indicate", word: "indicate", meaning: "나타내다, 가리키다", example: "The graph indicates a sharp recovery in scores.", exampleTranslation: "그래프는 점수의 급격한 회복을 나타낸다.", tags: ["reading"], stage: 1 },
  { id: "individual", word: "individual", meaning: "개인의, 개별적인", example: "Tailor your study plan to your individual pace.", exampleTranslation: "공부 계획을 자신만의 개인적 속도에 맞추라.", tags: ["logic"], stage: 1 },
  { id: "inefficient", word: "inefficient", meaning: "비효율적인", example: "Rereading without focus is an inefficient study habit.", exampleTranslation: "집중 없이 다시 읽는 것은 비효율적인 공부 습관이다.", tags: ["logic"], stage: 1 },
  { id: "influence", word: "influence", meaning: "영향을 미치다, 영향력", example: "Prior knowledge heavily influences reading comprehension.", exampleTranslation: "배경지식은 독해력에 큰 영향을 미친다.", tags: ["reading"], stage: 1 },
  { id: "insight", word: "insight", meaning: "통찰력, 이해", example: "The article provides deep insight into human cognition.", exampleTranslation: "그 기사는 인간 인지에 대한 깊은 통찰을 제공한다.", tags: ["reading"], stage: 1 },
  { id: "intent", word: "intent", meaning: "의도, 목적", example: "What is the author's main intent in this passage?", exampleTranslation: "이 지문에서 저자의 주된 의도는 무엇인가?", tags: ["reading"], stage: 1 },
  { id: "interpret", word: "interpret", meaning: "해석하다, 이해하다", example: "Learn to interpret data accurately from graphs.", exampleTranslation: "그래프에서 자료를 정확히 해석하는 법을 배워라.", tags: ["reading", "logic"], stage: 1 },
  { id: "investigate", word: "investigate", meaning: "조사하다, 연구하다", example: "Researchers investigate how sleep affects memory.", exampleTranslation: "연구원들은 수면이 기억에 미치는 영향을 조사한다.", tags: ["reading"], stage: 1 },
  { id: "justify", word: "justify", meaning: "정당화하다, 근거를 대다", example: "You must justify your choice using evidence from the text.", exampleTranslation: "글의 근거를 사용해 자신의 선택을 정당화해야 한다.", tags: ["writing", "reading"], stage: 1 },
  { id: "maintain", word: "maintain", meaning: "유지하다, 주장하다", example: "Maintain a steady routine even on weekends.", exampleTranslation: "주말에도 꾸준한 루틴을 유지하라.", tags: ["logic"], stage: 1 },
  { id: "objective", word: "objective", meaning: "객관적인, 목표", example: "Try to stay objective when evaluating arguments.", exampleTranslation: "주장을 평가할 때는 객관성을 유지하려고 노력하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "obtain", word: "obtain", meaning: "얻다, 획득하다", example: "You can obtain key info from titles and topic sentences.", exampleTranslation: "제목과 주제문에서 핵심 정보를 얻을 수 있다.", tags: ["reading"], stage: 1 },
  { id: "opponent", word: "opponent", meaning: "상대, 반대자", example: "The essay addresses potential arguments from opponents.", exampleTranslation: "그 에세이는 반대자들의 잠재적 주장을 다룬다.", tags: ["reading", "logic"], stage: 1 },
  { id: "outcome", word: "outcome", meaning: "결과, 성과", example: "Consistent practice leads to a positive outcome.", exampleTranslation: "일관된 연습은 긍정적인 결과로 이어진다.", tags: ["logic"], stage: 1 },
  { id: "perceive", word: "perceive", meaning: "인지하다, 감각하다", example: "How we perceive difficulty determines our response.", exampleTranslation: "우리가 난이도를 어떻게 인지하느냐가 우리의 반응을 결정한다.", tags: ["reading"], stage: 1 },
  { id: "predict", word: "predict", meaning: "예측하다", example: "Predict the next sentence based on transition words.", exampleTranslation: "접속어를 바탕으로 다음 문장을 예측하라.", tags: ["reading"], stage: 1 },
  { id: "prevalent", word: "prevalent", meaning: "널리 퍼진, 유행하는", example: "Common misconceptions are prevalent among beginners.", exampleTranslation: "흔한 오해들이 초보자들 사이에 널리 퍼져 있다.", tags: ["reading"], stage: 1 },
  { id: "primary", word: "primary", meaning: "주요한, 최초의", example: "The primary cause of failure is hasty guessing.", exampleTranslation: "실패의 주요 원인은 성급한 추측이다.", tags: ["reading", "logic"], stage: 1 },
  { id: "principle", word: "principle", meaning: "원칙, 원리", example: "Understanding basic math principles solves complex problems.", exampleTranslation: "기본 수학 원리를 이해하면 복잡한 문제가 풀린다.", tags: ["logic"], stage: 1 },
  { id: "prompt", word: "prompt", meaning: "신속한, 자극하다, 지문/발문", example: "Read the prompt carefully before reading options.", exampleTranslation: "선지를 읽기 전에 발문을 주의 깊게 읽어라.", tags: ["reading"], stage: 1 },
  { id: "proportion", word: "proportion", meaning: "비율, 부분", example: "A large proportion of questions focus on core concepts.", exampleTranslation: "많은 비율의 문제가 핵심 개념에 집중된다.", tags: ["reading", "logic"], stage: 1 },
  { id: "propose", word: "propose", meaning: "제안하다, 제시하다", example: "The researcher proposed a new method of analysis.", exampleTranslation: "연구자는 새로운 분석 방법을 제안했다.", tags: ["reading"], stage: 1 },
  { id: "reluctant", word: "reluctant", meaning: "꺼리는, 마지못해 하는", example: "Do not be reluctant to review basic grammar.", exampleTranslation: "기초 문법을 복습하는 것을 꺼리지 마라.", tags: ["reading"], stage: 1 },
  { id: "rely", word: "rely", meaning: "의존하다, 신뢰하다", example: "Do not rely solely on memory; write key notes down.", exampleTranslation: "기억에만 의존하지 말고 핵심 노트를 적어라.", tags: ["logic"], stage: 1 },
  { id: "resolve", word: "resolve", meaning: "해결하다, 결심하다", example: "Step-by-step breakdown resolves confusing questions.", exampleTranslation: "단계별 분해는 헷갈리는 문제를 해결해 준다.", tags: ["logic"], stage: 1 },
  { id: "reveal", word: "reveal", meaning: "드러내다, 밝히다", example: "A careful reading reveals the author's hidden view.", exampleTranslation: "주의 깊게 읽으면 저자의 숨은 견해가 드러난다.", tags: ["reading"], stage: 1 },
  { id: "scarce", word: "scarce", meaning: "부족한, 드문", example: "Time is scarce during actual exams, so pace yourself.", exampleTranslation: "실제 시험에서는 시간이 부족하므로 페이스를 조절하라.", tags: ["logic"], stage: 1 },
  { id: "skeptical", word: "skeptical", meaning: "회의적인, 의심하는", example: "Be skeptical of absolute claims containing 'always'.", exampleTranslation: "'항상'을 포함하는 절대적 주장에 회의적인 태도를 가져라.", tags: ["reading", "logic"], stage: 1 },
  { id: "subsequent", word: "subsequent", meaning: "그 다음의, 이어서 일어나는", example: "The first paragraph sets up all subsequent arguments.", exampleTranslation: "첫 문단이 그 뒤 이어지는 모든 주장을 설정한다.", tags: ["reading"], stage: 1 },
  { id: "sufficient", word: "sufficient", meaning: "충분한", example: "Provide sufficient evidence to back up your point.", exampleTranslation: "당신의 주장을 뒷받침할 충분한 근거를 제공하라.", tags: ["writing", "logic"], stage: 1 },
  { id: "support", word: "support", meaning: "지지하다, 뒷받침하다", example: "Every paragraph should support the central thesis.", exampleTranslation: "모든 문단은 중심 논지를 뒷받침해야 한다.", tags: ["reading", "writing"], stage: 1 },
  { id: "tendency", word: "tendency", meaning: "경향, 성향", example: "Students have a tendency to skip basic definitions.", exampleTranslation: "학생들은 기본 정의를 건너뛰는 경향이 있다.", tags: ["logic"], stage: 1 },
  { id: "ultimate", word: "ultimate", meaning: "궁극적인, 최종적인", example: "The ultimate goal is independent problem solving.", exampleTranslation: "궁극적인 목표는 독립적인 문제 해결이다.", tags: ["logic"], stage: 1 },
  { id: "underlie", word: "underlie", meaning: "~의 기저를 이루다", example: "Basic math concepts underlie advanced calculus.", exampleTranslation: "기본 수학 개념이 고등 미적분의 기저를 이룬다.", tags: ["logic"], stage: 1 },
  { id: "undertake", word: "undertake", meaning: "맡다, 착수하다", example: "Undertake a daily review habit for guaranteed growth.", exampleTranslation: "보장된 성장을 위해 매일 복습하는 습관에 착수하라.", tags: ["logic"], stage: 1 },
  { id: "vary", word: "vary", meaning: "다르다, 변하다", example: "Question types vary, but core reading principles stay.", exampleTranslation: "문제 유형은 변하지만 독해의 핵심 원리는 남아있다.", tags: ["reading"], stage: 1 },
  { id: "vital", word: "vital", meaning: "매우 중요한, 필수적인", example: "Focusing on verb tenses is vital for accuracy.", exampleTranslation: "동사 시제에 집중하는 것은 정확성을 위해 매우 중요하다.", tags: ["reading"], stage: 1 },
  { id: "vulnerable", word: "vulnerable", meaning: "취약한", example: "Without vocabulary, your reading strategy is vulnerable.", exampleTranslation: "어휘 없이 독해 전략은 취약해진다.", tags: ["reading"], stage: 1 },
  { id: "yield", word: "yield", meaning: "산출하다, 양보하다", example: "Active note-taking yields higher retention rates.", exampleTranslation: "능동적인 노트 필기는 더 높은 기억 유지율을 낳는다.", tags: ["logic"], stage: 1 },
  { id: "accommodate", word: "accommodate", meaning: "수용하다, 공간을 제공하다", example: "The schedule can accommodate individual learning needs.", exampleTranslation: "그 계획표는 개별 학습 요구를 수용할 수 있다.", tags: ["reading"], stage: 1 },
  { id: "accumulate", word: "accumulate", meaning: "축적하다, 모으다", example: "Knowledge accumulates through daily review.", exampleTranslation: "지식은 매일 하는 복습을 통해 축적된다.", tags: ["logic"], stage: 1 },
  { id: "acknowledge", word: "acknowledge", meaning: "인정하다, 승인하다", example: "The writer acknowledges opposing arguments before answering.", exampleTranslation: "필자는 답변하기 전에 반대 주장을 인정한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "acquire", word: "acquire", meaning: "습득하다, 얻다", example: "It takes time to acquire advanced reading skills.", exampleTranslation: "고급 독해 기술을 습득하는 데는 시간이 걸린다.", tags: ["reading"], stage: 1 },
  { id: "adapt", word: "adapt", meaning: "적응하다, 개작하다", example: "Successful students adapt their strategy to question types.", exampleTranslation: "성공적인 학생들은 문제 유형에 맞춰 전략을 적응시킨다.", tags: ["logic"], stage: 1 },
  { id: "adequate", word: "adequate", meaning: "적절한, 충분한", example: "Provide adequate reason for your chosen answer.", exampleTranslation: "자신이 선택한 답에 대한 적절한 이유를 대라.", tags: ["writing", "logic"], stage: 1 },
  { id: "advocate", word: "advocate", meaning: "옹호하다, 주장하다", example: "The essay advocates a balanced approach to technology.", exampleTranslation: "그 에세이는 기술에 대한 균형 잡힌 접근법을 옹호한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "affect", word: "affect", meaning: "영향을 미치다", example: "Stress can negatively affect test performance.", exampleTranslation: "스트레스는 시험 성적에 부정적인 영향을 미칠 수 있다.", tags: ["reading"], stage: 1 },
  { id: "alter", word: "alter", meaning: "바꾸다, 변하다", example: "New evidence forced the scientist to alter his theory.", exampleTranslation: "새 증거는 과학자로 하여금 그의 이론을 바꾸게 했다.", tags: ["reading", "logic"], stage: 1 },
  { id: "ambiguous", word: "ambiguous", meaning: "모호한, 다의적인", example: "Avoid ambiguous terms in academic summaries.", exampleTranslation: "학술 요약본에서 모호한 용어를 피하라.", tags: ["writing", "reading"], stage: 1 },
  { id: "anticipate", word: "anticipate", meaning: "예상하다, 기대하다", example: "Good readers anticipate the next argument.", exampleTranslation: "좋은 독자는 다음 주장을 예상한다.", tags: ["reading"], stage: 1 },
  { id: "apparent", word: "apparent", meaning: "명백한, 외견상의", example: "The solution became apparent after drawing a diagram.", exampleTranslation: "도형을 그린 후 해결책이 명백해졌다.", tags: ["logic"], stage: 1 },
  { id: "appeal", word: "appeal", meaning: "호소하다, 매력", example: "The writer appeals to the reader's emotions.", exampleTranslation: "필자는 독자의 감정에 호소한다.", tags: ["reading"], stage: 1 },
  { id: "appreciate", word: "appreciate", meaning: "진가를 알아보다, 감사하다", example: "To appreciate literature, look beyond literal meanings.", exampleTranslation: "문학의 진가를 알아보려면 문자 그대로의 의미를 넘어 보라.", tags: ["reading"], stage: 1 },
  { id: "approximate", word: "approximate", meaning: "대략의, 가깝다", example: "Calculate an approximate answer first to avoid big errors.", exampleTranslation: "큰 실수를 피하기 위해 먼저 대략의 답을 계산하라.", tags: ["logic"], stage: 1 },
  { id: "assert", word: "assert", meaning: "주장하다, 단언하다", example: "The author asserts that habit shapes human nature.", exampleTranslation: "저자는 습관이 인간의 본성을 형성한다고 주장한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "assess", word: "assess", meaning: "평가하다, 산정하다", example: "Assess your weak areas after every mock exam.", exampleTranslation: "매 모의고사 후 취약 영역을 평가하라.", tags: ["logic"], stage: 1 },
  { id: "associate", word: "associate", meaning: "연관짓다, 동료", example: "Associate new vocabulary with familiar images.", exampleTranslation: "새 단어를 친숙한 이미지와 연관 지으라.", tags: ["reading"], stage: 1 },
  { id: "bias", word: "bias", meaning: "편견, 편향", example: "Recognize personal bias when reading news articles.", exampleTranslation: "뉴스 기사를 읽을 때 개인적 편향을 인식하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "clarify", word: "clarify", meaning: "명확하게 하다", example: "A simple diagram helps clarify complex relationships.", exampleTranslation: "단순한 도식이 복잡한 관계를 명확히 하는 데 도움이 된다.", tags: ["writing", "logic"], stage: 1 },
  { id: "coherent", word: "coherent", meaning: "일관성 있는, 조리 있는", example: "A coherent paragraph has one central focus.", exampleTranslation: "조리 있는 문단은 하나의 중심 초점을 가진다.", tags: ["writing", "reading"], stage: 1 },
  { id: "coincide", word: "coincide", meaning: "일치하다, 동시에 일어나다", example: "The exam date coincides with the end of the term.", exampleTranslation: "시험 날짜가 학기 말과 일치한다.", tags: ["reading"], stage: 1 },
  { id: "compensate", word: "compensate", meaning: "보상하다, 보완하다", example: "Strategy can compensate for temporary memory loss.", exampleTranslation: "전략은 일시적인 기억력 저하를 보완할 수 있다.", tags: ["logic"], stage: 1 },
  { id: "complex", word: "complex", meaning: "복잡한, 복합체", example: "Break complex sentences into smaller chunks.", exampleTranslation: "복잡한 문장을 더 작은 덩어리로 나누라.", tags: ["reading"], stage: 1 },
  { id: "comply", word: "comply", meaning: "따르다, 준수하다", example: "Make sure your answer complies with the given prompt.", exampleTranslation: "답이 주어진 발문에 따르는지 확인하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "comprehend", word: "comprehend", meaning: "이해하다, 파악하다", example: "Read slowly to fully comprehend difficult texts.", exampleTranslation: "어려운 글을 완전히 이해하려면 천천히 읽으라.", tags: ["reading"], stage: 1 },
  { id: "concentrate", word: "concentrate", meaning: "집중하다", example: "Concentrate on main ideas rather than minor details.", exampleTranslation: "사소한 세부보다 중심 생각에 집중하라.", tags: ["reading"], stage: 1 },
  { id: "confirm", word: "confirm", meaning: "확인하다, 확정하다", example: "Always confirm your answer by checking text evidence.", exampleTranslation: "글의 근거를 확인하여 항상 답을 확정하라.", tags: ["reading", "logic"], stage: 1 },
  { id: "conflict", word: "conflict", meaning: "갈등, 충돌하다", example: "Character conflict drives the narrative forward.", exampleTranslation: "등장인물의 갈등이 서사를 앞으로 이끈다.", tags: ["reading"], stage: 1 },
  { id: "conform", word: "conform", meaning: "순응하다, 일치하다", example: "The data must conform to mathematical rules.", exampleTranslation: "자료는 수학적 규칙에 일치해야 한다.", tags: ["logic"], stage: 1 },
  { id: "confuse", word: "confuse", meaning: "혼동하다, 당황하게 하다", example: "Do not confuse cause with effect in reading.", exampleTranslation: "독해에서 원인과 결과를 혼동하지 마라.", tags: ["logic"], stage: 1 },
  { id: "consecutive", word: "consecutive", meaning: "연속적인", example: "Achieve 3 consecutive correct answers before moving on.", exampleTranslation: "넘어가기 전에 연속 3문제를 맞히라.", tags: ["logic"], stage: 1 },
  { id: "consensus", word: "consensus", meaning: "합의, 의견 일치", example: "Scientists reached a consensus on climate trends.", exampleTranslation: "과학자들은 기후 경향에 대해 합의에 도달했다.", tags: ["reading"], stage: 1 },
  { id: "considerable", word: "considerable", meaning: "상당한, 중요한", example: "Practice requires a considerable investment of time.", exampleTranslation: "연습에는 상당한 시간 투자가 필요하다.", tags: ["logic"], stage: 1 },
  { id: "constitute", word: "constitute", meaning: "구성하다, ~이 되다", example: "Core terms constitute the backbone of vocabulary.", exampleTranslation: "핵심 용어들이 어휘의 뼈대를 구성한다.", tags: ["reading"], stage: 1 },
  { id: "constraint", word: "constraint", meaning: "제약, 구속", example: "Time constraint is a major factor in test taking.", exampleTranslation: "시간 제약은 시험 치르기의 주요 요인이다.", tags: ["logic"], stage: 1 },
  { id: "contradict", word: "contradict", meaning: "모순되다, 반박하다", example: "The finding contradicts previous theories.", exampleTranslation: "그 발견은 이전 이론들과 모순된다.", tags: ["reading", "logic"], stage: 1 },
  { id: "contribute", word: "contribute", meaning: "기여하다, 원인이 되다", example: "Regular review contributes to steady grade improvement.", exampleTranslation: "정기적인 복습은 꾸준한 성적 향상에 기여한다.", tags: ["logic"], stage: 1 },
  { id: "conventional", word: "conventional", meaning: "관습적인, 종전의", example: "The author challenges conventional assumptions.", exampleTranslation: "저자는 관습적인 가정에 도전한다.", tags: ["reading"], stage: 1 },
  { id: "cooperate", word: "cooperate", meaning: "협력하다", example: "Group discussions help students cooperate on problems.", exampleTranslation: "조별 토론은 학생들이 문제 해결에 협력하도록 돕는다.", tags: ["reading"], stage: 1 },
  { id: "curtail", word: "curtail", meaning: "축소시키다, 줄이다", example: "Curtail distraction during 25-minute focus study.", exampleTranslation: "25분 집중 공부 중 산만함을 축소시키라.", tags: ["logic"], stage: 1 },
  { id: "deduce", word: "deduce", meaning: "연쇄 추론하다, 연덕하다", example: "We can deduce the answer from given facts.", exampleTranslation: "주어진 사실들로부터 답을 추론해낼 수 있다.", tags: ["logic", "reading"], stage: 1 },
  { id: "define", word: "define", meaning: "정의하다, 구별하다", example: "Clear concepts define effective study habits.", exampleTranslation: "명확한 개념이 효과적인 공부 습관을 정의한다.", tags: ["logic"], stage: 1 },
  { id: "deliberate", word: "deliberate", meaning: "의도적인, 신중한", example: "Make a deliberate choice based on evidence.", exampleTranslation: "근거를 바탕으로 신중한 선택을 내리라.", tags: ["reading", "logic"], stage: 1 },
  { id: "depict", word: "depict", meaning: "묘사하다, 그리다", example: "The novel depicts rural life in the 20th century.", exampleTranslation: "그 소설은 20세기 시골 삶을 묘사한다.", tags: ["reading"], stage: 1 },
  { id: "deprive", word: "deprive", meaning: "빼앗다, 박탈하다", example: "Lack of sleep deprives the brain of memory consolidation.", exampleTranslation: "수면 부족은 뇌에서 기억 정착을 빼앗는다.", tags: ["logic"], stage: 1 },
  { id: "deteriorate", word: "deteriorate", meaning: "악화되다, 저하되다", example: "Focus deteriorates after hours without rest.", exampleTranslation: "휴식 없이 몇 시간이 지나면 집중력이 악화된다.", tags: ["logic"], stage: 1 },
  { id: "deviate", word: "deviate", meaning: "벗어나다, 일탈하다", example: "Do not deviate from the text evidence when answering.", exampleTranslation: "답할 때 글의 근거에서 벗어나지 마라.", tags: ["reading", "logic"], stage: 1 },
  { id: "diminish", word: "diminish", meaning: "줄어들다, 약화시키다", example: "Doubts diminish as practice builds competence.", exampleTranslation: "역량이 쌓임에 따라 의구심은 줄어든다.", tags: ["logic"], stage: 1 },
  { id: "disprove", word: "disprove", meaning: "반증하다, 오류를 입증하다", example: "New data disproved the old hypothesis.", exampleTranslation: "새 자료가 오래된 가설의 오류를 입증했다.", tags: ["reading", "logic"], stage: 1 },
  { id: "disrupt", word: "disrupt", meaning: "방해하다, 혼란에 빠뜨리다", example: "Noise can disrupt your deep reading flow.", exampleTranslation: "소음은 깊은 독해 흐름을 방해할 수 있다.", tags: ["logic"], stage: 1 },
  { id: "distort", word: "distort", meaning: "왜곡하다, 비틀다", example: "Bias can distort objective facts in articles.", exampleTranslation: "편향은 기사의 객관적 사실을 왜곡할 수 있다.", tags: ["reading"], stage: 1 },
  { id: "diverse", word: "diverse", meaning: "다양한", example: "Read diverse passages to broaden vocabulary.", exampleTranslation: "어휘를 넓히기 위해 다양한 지문을 읽으라.", tags: ["reading"], stage: 1 },
  { id: "domain", word: "domain", meaning: "영역, 분야", example: "Mathematics is a core domain in entrance exams.", exampleTranslation: "수학은 입시 시험에서 핵심 영역이다.", tags: ["logic"], stage: 1 },
  { id: "drastic", word: "drastic", meaning: "과감한, 급격한", example: "A drastic change in routine requires strong motivation.", exampleTranslation: "루틴의 급격한 변화에는 강한 동기가 필요하다.", tags: ["logic"], stage: 1 },
  { id: "durable", word: "durable", meaning: "내구성 있는, 오래가는", example: "SRS study builds durable memory retention.", exampleTranslation: "SRS 공부법은 오래가는 기억력을 만들어 준다.", tags: ["logic"], stage: 1 },
  { id: "elaborate", word: "elaborate", meaning: "정교한, 정교하게 설명하다", example: "Elaborate on your reasoning using exact quotes.", exampleTranslation: "정확한 인용을 사용해 추론을 정교하게 설명하라.", tags: ["writing", "reading"], stage: 1 },
  { id: "empirical", word: "empirical", meaning: "경험적인, 실증적인", example: "Empirical studies confirm the value of testing yourself.", exampleTranslation: "실증적 연구는 자가 테스트의 가치를 확인해 준다.", tags: ["reading", "logic"], stage: 1 },
  { id: "accept", word: "accept", meaning: "받아들이다, 수락하다", example: "She accepted my apology right away.", exampleTranslation: "그녀는 내 사과를 바로 받아들였다.", tags: ["listening", "reading"], stage: 1 },
  { id: "achieve", word: "achieve", meaning: "이루다, 달성하다", example: "You can achieve your goal with daily effort.", exampleTranslation: "매일의 노력으로 목표를 이룰 수 있다.", tags: ["logic"], stage: 1 },
  { id: "add", word: "add", meaning: "더하다, 추가하다", example: "Add one more example to your answer.", exampleTranslation: "답에 예시를 하나 더 추가하라.", tags: ["writing"], stage: 1 },
  { id: "admit", word: "admit", meaning: "인정하다, 시인하다", example: "He admitted that he forgot the homework.", exampleTranslation: "그는 숙제를 잊었다고 인정했다.", tags: ["listening", "reading"], stage: 1 },
  { id: "advise", word: "advise", meaning: "조언하다, 충고하다", example: "My teacher advised me to read aloud.", exampleTranslation: "선생님은 나에게 소리 내어 읽으라고 조언하셨다.", tags: ["listening"], stage: 1 },
  { id: "afford", word: "afford", meaning: "~할 여유가 있다", example: "We cannot afford to waste study time.", exampleTranslation: "우리는 공부 시간을 낭비할 여유가 없다.", tags: ["reading"], stage: 1 },
  { id: "agree", word: "agree", meaning: "동의하다", example: "Most students agree with this simple rule.", exampleTranslation: "대부분의 학생들이 이 단순한 규칙에 동의한다.", tags: ["listening", "reading"], stage: 1 },
  { id: "allow", word: "allow", meaning: "허락하다, 가능하게 하다", example: "The teacher allows one short break.", exampleTranslation: "선생님은 짧은 휴식 하나를 허락하신다.", tags: ["listening"], stage: 1 },
  { id: "announce", word: "announce", meaning: "발표하다, 알리다", example: "The school announced the exam date today.", exampleTranslation: "학교는 오늘 시험 날짜를 발표했다.", tags: ["listening"], stage: 1 },
  { id: "apologize", word: "apologize", meaning: "사과하다", example: "He apologized for being late again.", exampleTranslation: "그는 또 늦은 것에 대해 사과했다.", tags: ["listening"], stage: 1 },
  { id: "appear", word: "appear", meaning: "나타나다, ~처럼 보이다", example: "The answer appears simple at first.", exampleTranslation: "그 답은 처음에는 단순해 보인다.", tags: ["reading"], stage: 1 },
  { id: "apply", word: "apply", meaning: "적용하다, 지원하다", example: "Apply the same rule to the next question.", exampleTranslation: "같은 규칙을 다음 문제에도 적용하라.", tags: ["logic", "reading"], stage: 1 },
  { id: "argue", word: "argue", meaning: "주장하다, 논쟁하다", example: "The writer argues that habits shape us.", exampleTranslation: "필자는 습관이 우리를 만든다고 주장한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "arrange", word: "arrange", meaning: "배열하다, 준비하다", example: "Arrange the sentences in the right order.", exampleTranslation: "문장들을 올바른 순서로 배열하라.", tags: ["reading", "writing"], stage: 1 },
  { id: "arrive", word: "arrive", meaning: "도착하다", example: "The bus arrives at eight every morning.", exampleTranslation: "그 버스는 매일 아침 8시에 도착한다.", tags: ["listening"], stage: 1 },
  { id: "attach", word: "attach", meaning: "붙이다, 첨부하다", example: "Attach a short note to each page.", exampleTranslation: "각 페이지에 짧은 메모를 붙여라.", tags: ["writing"], stage: 1 },
  { id: "attend", word: "attend", meaning: "참석하다, 다니다", example: "She attends a small English class.", exampleTranslation: "그녀는 작은 영어 수업에 다닌다.", tags: ["listening"], stage: 1 },
  { id: "attract", word: "attract", meaning: "끌어당기다, 매혹하다", example: "Bright colors attract the reader's eye.", exampleTranslation: "밝은 색은 독자의 눈을 끌어당긴다.", tags: ["reading"], stage: 1 },
  { id: "avoid", word: "avoid", meaning: "피하다", example: "Avoid careless mistakes on easy questions.", exampleTranslation: "쉬운 문제에서 부주의한 실수를 피하라.", tags: ["logic"], stage: 1 },
  { id: "believe", word: "believe", meaning: "믿다", example: "I believe you can finish this book.", exampleTranslation: "나는 네가 이 책을 끝낼 수 있다고 믿는다.", tags: ["listening", "reading"], stage: 1 },
  { id: "belong", word: "belong", meaning: "속하다, ~의 것이다", example: "This word belongs to the science unit.", exampleTranslation: "이 단어는 과학 단원에 속한다.", tags: ["reading"], stage: 1 },
  { id: "borrow", word: "borrow", meaning: "빌리다", example: "You can borrow this book for a week.", exampleTranslation: "이 책을 일주일 동안 빌릴 수 있다.", tags: ["listening"], stage: 1 },
  { id: "break", word: "break", meaning: "깨다, 부수다, 휴식", example: "Take a short break every fifty minutes.", exampleTranslation: "50분마다 짧은 휴식을 가져라.", tags: ["listening", "logic"], stage: 1 },
  { id: "bring", word: "bring", meaning: "가져오다, 데려오다", example: "Bring your notebook to every class.", exampleTranslation: "모든 수업에 공책을 가져와라.", tags: ["listening"], stage: 1 },
  { id: "build", word: "build", meaning: "짓다, 쌓아 올리다", example: "Daily reading builds real vocabulary power.", exampleTranslation: "매일의 독서가 진짜 어휘력을 쌓아 올린다.", tags: ["reading"], stage: 1 },
  { id: "burn", word: "burn", meaning: "타다, 태우다", example: "The candle burned all night long.", exampleTranslation: "그 초는 밤새도록 탔다.", tags: ["reading"], stage: 1 },
  { id: "calculate", word: "calculate", meaning: "계산하다", example: "Calculate the answer before checking the choices.", exampleTranslation: "선지를 확인하기 전에 답을 계산하라.", tags: ["logic"], stage: 1 },
  { id: "care", word: "care", meaning: "신경 쓰다, 돌보다", example: "She cares about every small detail.", exampleTranslation: "그녀는 모든 사소한 세부에 신경 쓴다.", tags: ["listening", "reading"], stage: 1 },
  { id: "carry", word: "carry", meaning: "나르다, 가지고 다니다", example: "I carry a small word list everywhere.", exampleTranslation: "나는 작은 단어장을 어디에나 가지고 다닌다.", tags: ["reading"], stage: 1 },
  { id: "catch", word: "catch", meaning: "잡다, 알아채다", example: "Try to catch the main idea quickly.", exampleTranslation: "중심 생각을 빨리 잡아내려고 해 보라.", tags: ["reading", "listening"], stage: 1 },
  { id: "cause", word: "cause", meaning: "야기하다, 원인", example: "Careless reading causes most wrong answers.", exampleTranslation: "부주의한 독해가 대부분의 오답을 낳는다.", tags: ["logic"], stage: 1 },
  { id: "celebrate", word: "celebrate", meaning: "축하하다, 기념하다", example: "We celebrate small wins every week.", exampleTranslation: "우리는 매주 작은 성공을 축하한다.", tags: ["listening"], stage: 1 },
  { id: "change", word: "change", meaning: "바꾸다, 변화", example: "One small change can fix your routine.", exampleTranslation: "작은 변화 하나가 네 루틴을 고칠 수 있다.", tags: ["logic"], stage: 1 },
  { id: "check", word: "check", meaning: "확인하다, 점검하다", example: "Check your answer against the passage.", exampleTranslation: "지문과 대조하여 답을 확인하라.", tags: ["reading"], stage: 1 },
  { id: "choose", word: "choose", meaning: "고르다, 선택하다", example: "Choose the answer with clear evidence.", exampleTranslation: "명확한 근거가 있는 답을 골라라.", tags: ["reading", "logic"], stage: 1 },
  { id: "climb", word: "climb", meaning: "오르다, 등반하다", example: "They climbed the hill before sunrise.", exampleTranslation: "그들은 해 뜨기 전에 언덕을 올랐다.", tags: ["reading"], stage: 1 },
  { id: "collect", word: "collect", meaning: "모으다, 수집하다", example: "Collect new words in one small notebook.", exampleTranslation: "새 단어를 작은 공책 하나에 모아라.", tags: ["reading"], stage: 1 },
  { id: "communicate", word: "communicate", meaning: "의사소통하다, 전달하다", example: "Good writers communicate ideas in plain words.", exampleTranslation: "좋은 필자는 생각을 쉬운 말로 전달한다.", tags: ["writing"], stage: 1 },
  { id: "complain", word: "complain", meaning: "불평하다", example: "He complained about the noisy classroom.", exampleTranslation: "그는 시끄러운 교실에 대해 불평했다.", tags: ["listening"], stage: 1 },
  { id: "complete", word: "complete", meaning: "완성하다, 완전한", example: "Complete one page before you rest.", exampleTranslation: "쉬기 전에 한 쪽을 완성하라.", tags: ["logic"], stage: 1 },
  { id: "connect", word: "connect", meaning: "연결하다", example: "Connect each new word to a sentence.", exampleTranslation: "각 새 단어를 한 문장과 연결하라.", tags: ["reading"], stage: 1 },
  { id: "consider", word: "consider", meaning: "고려하다, ~로 여기다", example: "Consider both sides before you decide.", exampleTranslation: "결정하기 전에 양쪽을 모두 고려하라.", tags: ["logic", "reading"], stage: 1 },
  { id: "contain", word: "contain", meaning: "담고 있다, 포함하다", example: "This passage contains two opposite views.", exampleTranslation: "이 지문은 상반된 두 견해를 담고 있다.", tags: ["reading"], stage: 1 },
  { id: "continue", word: "continue", meaning: "계속하다", example: "Continue the routine even on bad days.", exampleTranslation: "컨디션이 나쁜 날에도 루틴을 계속하라.", tags: ["logic"], stage: 1 },
  { id: "control", word: "control", meaning: "통제하다, 통제", example: "You can control your pace during tests.", exampleTranslation: "시험 중에는 자신의 속도를 통제할 수 있다.", tags: ["logic"], stage: 1 },
  { id: "copy", word: "copy", meaning: "베끼다, 복사하다, 사본", example: "Do not copy answers without understanding them.", exampleTranslation: "이해하지 않고 답을 베끼지 마라.", tags: ["logic"], stage: 1 },
  { id: "correct", word: "correct", meaning: "옳은, 고치다", example: "Mark the correct answer with a circle.", exampleTranslation: "옳은 답에 동그라미를 쳐라.", tags: ["reading"], stage: 1 },
  { id: "count", word: "count", meaning: "세다, 중요하다", example: "Every quiet hour counts in the end.", exampleTranslation: "결국 조용한 한 시간 한 시간이 중요하다.", tags: ["logic"], stage: 1 },
  { id: "cover", word: "cover", meaning: "덮다, 다루다", example: "This unit covers three basic tenses.", exampleTranslation: "이 단원은 기본 시제 세 가지를 다룬다.", tags: ["reading"], stage: 1 },
  { id: "create", word: "create", meaning: "만들다, 창조하다", example: "Create your own example for each word.", exampleTranslation: "각 단어마다 자신만의 예문을 만들어라.", tags: ["writing"], stage: 1 },
  { id: "cross", word: "cross", meaning: "건너다, 가로지르다", example: "Look both ways before you cross.", exampleTranslation: "건너기 전에 양쪽을 살펴라.", tags: ["listening"], stage: 1 },
  { id: "decide", word: "decide", meaning: "결정하다", example: "Decide the answer, then check the evidence.", exampleTranslation: "답을 정한 다음 근거를 확인하라.", tags: ["logic"], stage: 1 },
  { id: "deliver", word: "deliver", meaning: "배달하다, 전달하다", example: "The speaker delivered a short clear message.", exampleTranslation: "연사는 짧고 명확한 메시지를 전달했다.", tags: ["listening"], stage: 1 },
  { id: "deny", word: "deny", meaning: "부인하다, 거부하다", example: "He denied any part in the mistake.", exampleTranslation: "그는 그 실수에 관여했음을 부인했다.", tags: ["reading"], stage: 1 },
  { id: "depend", word: "depend", meaning: "의존하다, ~에 달려 있다", example: "The meaning depends on the whole sentence.", exampleTranslation: "그 의미는 문장 전체에 달려 있다.", tags: ["reading"], stage: 1 },
  { id: "describe", word: "describe", meaning: "묘사하다, 설명하다", example: "Describe the graph in one short sentence.", exampleTranslation: "그 그래프를 짧은 한 문장으로 설명하라.", tags: ["writing"], stage: 1 },
  { id: "design", word: "design", meaning: "설계하다, 디자인", example: "We designed a simple weekly plan.", exampleTranslation: "우리는 단순한 주간 계획을 설계했다.", tags: ["logic"], stage: 1 },
  { id: "destroy", word: "destroy", meaning: "파괴하다, 무너뜨리다", example: "One careless habit can destroy your progress.", exampleTranslation: "부주의한 습관 하나가 네 진전을 무너뜨릴 수 있다.", tags: ["logic"], stage: 1 },
  { id: "develop", word: "develop", meaning: "발전시키다, 개발하다", example: "Reading aloud develops natural sentence rhythm.", exampleTranslation: "소리 내어 읽기는 자연스러운 문장 리듬을 길러 준다.", tags: ["listening", "reading"], stage: 1 },
  { id: "disappear", word: "disappear", meaning: "사라지다", example: "The fear disappears after enough practice.", exampleTranslation: "충분한 연습 후에는 두려움이 사라진다.", tags: ["logic"], stage: 1 },
  { id: "discover", word: "discover", meaning: "발견하다", example: "You will discover patterns in wrong answers.", exampleTranslation: "오답에서 반복되는 패턴을 발견하게 될 것이다.", tags: ["logic"], stage: 1 },
  { id: "discuss", word: "discuss", meaning: "논의하다, 다루다", example: "The article discusses two study methods.", exampleTranslation: "그 기사는 두 가지 공부법을 논의한다.", tags: ["reading"], stage: 1 },
  { id: "divide", word: "divide", meaning: "나누다, 분할하다", example: "Divide the passage into three parts.", exampleTranslation: "지문을 세 부분으로 나누라.", tags: ["reading"], stage: 1 },
  { id: "doubt", word: "doubt", meaning: "의심하다, 의심", example: "Do not doubt your basic reading skill.", exampleTranslation: "네 기본 독해력을 의심하지 마라.", tags: ["logic"], stage: 1 },
  { id: "draw", word: "draw", meaning: "그리다, 끌어내다", example: "Draw a simple map of the argument.", exampleTranslation: "주장의 흐름을 간단한 지도로 그려라.", tags: ["logic"], stage: 1 },
  { id: "dream", word: "dream", meaning: "꿈, 꿈꾸다", example: "She dreams of studying in another country.", exampleTranslation: "그녀는 다른 나라에서 공부하는 꿈을 꾼다.", tags: ["listening"], stage: 1 },
  { id: "earn", word: "earn", meaning: "벌다, 얻다", example: "You earn confidence by finishing small tasks.", exampleTranslation: "작은 과제를 끝내면서 자신감을 얻는다.", tags: ["logic"], stage: 1 },
  { id: "encourage", word: "encourage", meaning: "격려하다, 장려하다", example: "Teachers encourage students to ask questions.", exampleTranslation: "선생님들은 학생들이 질문하도록 격려한다.", tags: ["listening"], stage: 1 },
  { id: "enjoy", word: "enjoy", meaning: "즐기다", example: "I enjoy reading short English stories.", exampleTranslation: "나는 짧은 영어 이야기를 읽는 것을 즐긴다.", tags: ["reading"], stage: 1 },
  { id: "enter", word: "enter", meaning: "들어가다, 입력하다", example: "Please enter the room quietly.", exampleTranslation: "조용히 방에 들어가 주세요.", tags: ["listening"], stage: 1 },
  { id: "escape", word: "escape", meaning: "탈출하다, 벗어나다", example: "He escaped from the burning building safely.", exampleTranslation: "그는 불타는 건물에서 무사히 탈출했다.", tags: ["reading"], stage: 1 },
  { id: "examine", word: "examine", meaning: "조사하다, 살펴보다", example: "Examine each choice before you mark one.", exampleTranslation: "하나를 표시하기 전에 각 선지를 살펴보라.", tags: ["reading", "logic"], stage: 1 },
  { id: "exchange", word: "exchange", meaning: "교환하다, 교환", example: "We exchanged phone numbers after class.", exampleTranslation: "우리는 수업이 끝나고 전화번호를 교환했다.", tags: ["listening"], stage: 1 },
  { id: "exist", word: "exist", meaning: "존재하다", example: "No perfect study method exists for everyone.", exampleTranslation: "모두에게 완벽한 공부법은 존재하지 않는다.", tags: ["logic"], stage: 1 },
  { id: "expand", word: "expand", meaning: "확장하다, 넓히다", example: "Reading expands your vocabulary week by week.", exampleTranslation: "독서는 주마다 어휘를 넓혀 준다.", tags: ["reading"], stage: 1 },
  { id: "expect", word: "expect", meaning: "기대하다, 예상하다", example: "Do not expect progress in a single day.", exampleTranslation: "하루 만에 발전을 기대하지 마라.", tags: ["logic"], stage: 1 },
  { id: "experience", word: "experience", meaning: "경험, 경험하다", example: "Every student experiences a slow week sometimes.", exampleTranslation: "모든 학생은 가끔 더딘 한 주를 겪는다.", tags: ["logic"], stage: 1 },
  { id: "explain", word: "explain", meaning: "설명하다", example: "Explain the answer to yourself out loud.", exampleTranslation: "그 답을 스스로에게 소리 내어 설명하라.", tags: ["writing", "logic"], stage: 1 },
  { id: "explore", word: "explore", meaning: "탐구하다, 탐험하다", example: "The passage explores the history of writing.", exampleTranslation: "그 지문은 문자의 역사를 탐구한다.", tags: ["reading"], stage: 1 },
  { id: "express", word: "express", meaning: "표현하다, 나타내다", example: "Try to express one idea per sentence.", exampleTranslation: "한 문장에 하나의 생각만 표현하려고 하라.", tags: ["writing"], stage: 1 },
  { id: "fail", word: "fail", meaning: "실패하다, ~하지 못하다", example: "Many students fail to read the question.", exampleTranslation: "많은 학생들이 문제를 제대로 읽지 못한다.", tags: ["reading"], stage: 1 },
  { id: "fear", word: "fear", meaning: "두려움, 두려워하다", example: "Fear of mistakes slows your reading down.", exampleTranslation: "실수에 대한 두려움이 독해 속도를 늦춘다.", tags: ["logic"], stage: 1 },
  { id: "feed", word: "feed", meaning: "먹이다, 먹이", example: "She feeds her dog twice a day.", exampleTranslation: "그녀는 하루에 두 번 개에게 먹이를 준다.", tags: ["listening"], stage: 1 },
  { id: "fill", word: "fill", meaning: "채우다", example: "Fill the blank with a simple verb.", exampleTranslation: "빈칸을 간단한 동사로 채워라.", tags: ["writing"], stage: 1 },
  { id: "finish", word: "finish", meaning: "끝내다, 마치다", example: "Finish one small task before you stop.", exampleTranslation: "멈추기 전에 작은 과제 하나를 끝내라.", tags: ["logic"], stage: 1 },
  { id: "fix", word: "fix", meaning: "고치다, 고정하다", example: "Fix your weak grammar point this week.", exampleTranslation: "이번 주에는 약한 문법 포인트를 고쳐라.", tags: ["logic"], stage: 1 },
  { id: "follow", word: "follow", meaning: "따르다, 뒤따르다", example: "Follow the order of the passage carefully.", exampleTranslation: "지문의 순서를 주의 깊게 따라가라.", tags: ["reading"], stage: 1 },
  { id: "forget", word: "forget", meaning: "잊다", example: "We forget most words without regular review.", exampleTranslation: "규칙적인 복습 없이는 대부분의 단어를 잊는다.", tags: ["logic"], stage: 1 },
  { id: "forgive", word: "forgive", meaning: "용서하다", example: "Forgive yourself for one bad study day.", exampleTranslation: "공부가 안 된 하루쯤은 자신을 용서하라.", tags: ["listening"], stage: 1 },
  { id: "gather", word: "gather", meaning: "모으다, 모이다", example: "Gather your notes before the weekly review.", exampleTranslation: "주간 복습 전에 노트를 모아라.", tags: ["logic"], stage: 1 },
  { id: "grow", word: "grow", meaning: "자라다, 기르다", example: "Your reading speed grows with steady practice.", exampleTranslation: "독해 속도는 꾸준한 연습으로 자란다.", tags: ["reading"], stage: 1 },
  { id: "guess", word: "guess", meaning: "추측하다, 추측", example: "Guess the meaning before you check it.", exampleTranslation: "확인하기 전에 먼저 의미를 추측하라.", tags: ["reading"], stage: 1 },
  { id: "handle", word: "handle", meaning: "다루다, 처리하다", example: "She handles hard questions without panic.", exampleTranslation: "그녀는 어려운 문제를 당황하지 않고 다룬다.", tags: ["logic"], stage: 1 },
  { id: "happen", word: "happen", meaning: "일어나다, 발생하다", example: "Mistakes happen when you rush the last page.", exampleTranslation: "마지막 쪽을 서두를 때 실수가 일어난다.", tags: ["logic"], stage: 1 },
  { id: "hide", word: "hide", meaning: "숨다, 숨기다", example: "The main idea hides inside a long sentence.", exampleTranslation: "중심 생각이 긴 문장 속에 숨어 있다.", tags: ["reading"], stage: 1 },
  { id: "hire", word: "hire", meaning: "고용하다", example: "The company hired ten new workers.", exampleTranslation: "그 회사는 새 직원 열 명을 고용했다.", tags: ["reading"], stage: 1 },
  { id: "hurry", word: "hurry", meaning: "서두르다, 서두름", example: "Do not hurry through the last question.", exampleTranslation: "마지막 문제를 서둘러 넘기지 마라.", tags: ["logic"], stage: 1 },
  { id: "hurt", word: "hurt", meaning: "다치게 하다, 아프다", example: "Skipping sleep hurts your memory badly.", exampleTranslation: "잠을 거르는 것은 기억력을 심하게 해친다.", tags: ["logic"], stage: 1 },
  { id: "identify", word: "identify", meaning: "찾아내다, 식별하다", example: "Identify the subject of each long sentence.", exampleTranslation: "긴 문장마다 주어를 찾아내라.", tags: ["reading"], stage: 1 },
  { id: "ignore", word: "ignore", meaning: "무시하다", example: "Do not ignore the small linking words.", exampleTranslation: "작은 연결어들을 무시하지 마라.", tags: ["reading"], stage: 1 },
  { id: "imagine", word: "imagine", meaning: "상상하다", example: "Imagine the scene while you read it.", exampleTranslation: "읽으면서 그 장면을 머릿속에 그려 보라.", tags: ["reading"], stage: 1 },
  { id: "improve", word: "improve", meaning: "향상시키다, 나아지다", example: "Your listening improves with daily short clips.", exampleTranslation: "듣기는 매일 짧은 영상으로 나아진다.", tags: ["listening"], stage: 1 },
  { id: "introduce", word: "introduce", meaning: "소개하다, 도입하다", example: "The first paragraph introduces the main topic.", exampleTranslation: "첫 문단이 중심 화제를 소개한다.", tags: ["reading"], stage: 1 },
  { id: "invent", word: "invent", meaning: "발명하다", example: "He invented a simple machine for farmers.", exampleTranslation: "그는 농부들을 위한 간단한 기계를 발명했다.", tags: ["reading"], stage: 1 },
  { id: "invite", word: "invite", meaning: "초대하다", example: "They invited me to the school festival.", exampleTranslation: "그들은 나를 학교 축제에 초대했다.", tags: ["listening"], stage: 1 },
  { id: "involve", word: "involve", meaning: "포함하다, 관련시키다", example: "Good reading involves asking constant questions.", exampleTranslation: "좋은 독해는 끊임없이 질문하는 일을 포함한다.", tags: ["reading"], stage: 1 },
  { id: "join", word: "join", meaning: "참여하다, 합치다", example: "Join a small study group this month.", exampleTranslation: "이번 달에 작은 스터디 모임에 참여하라.", tags: ["listening"], stage: 1 },
  { id: "judge", word: "judge", meaning: "판단하다, 판사", example: "Do not judge a passage by its title.", exampleTranslation: "제목만 보고 지문을 판단하지 마라.", tags: ["reading", "logic"], stage: 1 },
  { id: "lack", word: "lack", meaning: "부족, 부족하다", example: "Most errors come from a lack of focus.", exampleTranslation: "대부분의 실수는 집중력 부족에서 온다.", tags: ["logic"], stage: 1 },
  { id: "laugh", word: "laugh", meaning: "웃다, 웃음", example: "We laughed at his funny English mistake.", exampleTranslation: "우리는 그의 웃긴 영어 실수에 웃었다.", tags: ["listening"], stage: 1 },
  { id: "lead", word: "lead", meaning: "이끌다, 이어지다", example: "Small daily steps lead to big results.", exampleTranslation: "매일의 작은 걸음이 큰 결과로 이어진다.", tags: ["logic"], stage: 1 },
  { id: "lend", word: "lend", meaning: "빌려주다", example: "Could you lend me your eraser?", exampleTranslation: "지우개 좀 빌려줄 수 있니?", tags: ["listening"], stage: 1 },
  { id: "lift", word: "lift", meaning: "들어 올리다", example: "He lifted the heavy box alone.", exampleTranslation: "그는 무거운 상자를 혼자 들어 올렸다.", tags: ["reading"], stage: 1 },
  { id: "limit", word: "limit", meaning: "제한하다, 한계", example: "Limit your phone time during study hours.", exampleTranslation: "공부 시간에는 휴대폰 사용을 제한하라.", tags: ["logic"], stage: 1 },
  { id: "locate", word: "locate", meaning: "위치를 찾다, 두다", example: "Locate the topic sentence in each paragraph.", exampleTranslation: "각 문단에서 주제문의 위치를 찾아라.", tags: ["reading"], stage: 1 },
  { id: "manage", word: "manage", meaning: "관리하다, 해내다", example: "She manages her time with a simple list.", exampleTranslation: "그녀는 간단한 목록으로 시간을 관리한다.", tags: ["logic"], stage: 1 },
  { id: "mark", word: "mark", meaning: "표시하다, 자국", example: "Mark the words you did not know.", exampleTranslation: "몰랐던 단어에 표시해 두어라.", tags: ["reading"], stage: 1 },
  { id: "measure", word: "measure", meaning: "측정하다, 조치", example: "Measure progress by weekly review, not mood.", exampleTranslation: "기분이 아니라 주간 복습으로 진전을 측정하라.", tags: ["logic"], stage: 1 },
  { id: "mention", word: "mention", meaning: "언급하다", example: "The writer mentions two famous experiments.", exampleTranslation: "필자는 유명한 실험 두 가지를 언급한다.", tags: ["reading"], stage: 1 },
  { id: "mix", word: "mix", meaning: "섞다, 혼합", example: "Do not mix new words with old ones.", exampleTranslation: "새 단어와 오래된 단어를 섞지 마라.", tags: ["logic"], stage: 1 },
  { id: "notice", word: "notice", meaning: "알아차리다, 공지", example: "Did you notice the small change in tone?", exampleTranslation: "어조의 작은 변화를 알아차렸니?", tags: ["listening", "reading"], stage: 1 },
  { id: "observe", word: "observe", meaning: "관찰하다, 준수하다", example: "Observe how the writer opens each paragraph.", exampleTranslation: "필자가 각 문단을 어떻게 여는지 관찰하라.", tags: ["reading"], stage: 1 },
  { id: "occur", word: "occur", meaning: "일어나다, 발생하다", example: "Careless errors occur in the last minutes.", exampleTranslation: "부주의한 실수는 마지막 몇 분에 일어난다.", tags: ["logic"], stage: 1 },
  { id: "offer", word: "offer", meaning: "제공하다, 제안", example: "The book offers many easy example sentences.", exampleTranslation: "그 책은 쉬운 예문을 많이 제공한다.", tags: ["reading"], stage: 1 },
  { id: "operate", word: "operate", meaning: "작동하다, 운영하다", example: "This method operates well for slow readers.", exampleTranslation: "이 방법은 느린 독자에게 잘 작동한다.", tags: ["logic"], stage: 1 },
  { id: "organize", word: "organize", meaning: "정리하다, 조직하다", example: "Organize your notes by question type.", exampleTranslation: "노트를 문제 유형별로 정리하라.", tags: ["writing", "logic"], stage: 1 },
  { id: "own", word: "own", meaning: "자신의, 소유하다", example: "Write the meaning in your own words.", exampleTranslation: "그 뜻을 네 자신의 말로 적어라.", tags: ["writing"], stage: 1 },
  { id: "participate", word: "participate", meaning: "참여하다", example: "Students participate in a short daily quiz.", exampleTranslation: "학생들은 매일 짧은 퀴즈에 참여한다.", tags: ["listening"], stage: 1 },
  { id: "perform", word: "perform", meaning: "수행하다, 공연하다", example: "Students perform better after enough sleep.", exampleTranslation: "학생들은 충분히 잔 뒤에 더 좋은 성과를 낸다.", tags: ["logic"], stage: 1 },
  { id: "permit", word: "permit", meaning: "허용하다, 허가", example: "The rules permit one short break.", exampleTranslation: "규칙은 짧은 휴식 한 번을 허용한다.", tags: ["reading"], stage: 1 },
  { id: "plan", word: "plan", meaning: "계획, 계획하다", example: "Plan tomorrow's study before you sleep.", exampleTranslation: "자기 전에 내일 공부를 계획하라.", tags: ["logic"], stage: 1 },
  { id: "praise", word: "praise", meaning: "칭찬하다, 칭찬", example: "Praise effort rather than natural talent.", exampleTranslation: "타고난 재능보다 노력을 칭찬하라.", tags: ["listening"], stage: 1 },
  { id: "prefer", word: "prefer", meaning: "더 좋아하다, 선호하다", example: "I prefer short passages in the morning.", exampleTranslation: "나는 아침에 짧은 지문을 더 좋아한다.", tags: ["listening"], stage: 1 },
  { id: "prepare", word: "prepare", meaning: "준비하다", example: "Prepare three questions before the lecture starts.", exampleTranslation: "강의가 시작되기 전에 질문 세 개를 준비하라.", tags: ["listening"], stage: 1 },
  { id: "prevent", word: "prevent", meaning: "막다, 예방하다", example: "A short plan prevents wasted study hours.", exampleTranslation: "짧은 계획이 낭비되는 공부 시간을 막아 준다.", tags: ["logic"], stage: 1 },
  { id: "produce", word: "produce", meaning: "생산하다, 만들어 내다", example: "Steady review produces steady exam scores.", exampleTranslation: "꾸준한 복습이 꾸준한 시험 점수를 만들어 낸다.", tags: ["logic"], stage: 1 },
  { id: "promise", word: "promise", meaning: "약속하다, 약속", example: "Promise yourself ten words every morning.", exampleTranslation: "매일 아침 열 단어를 스스로에게 약속하라.", tags: ["logic"], stage: 1 },
  { id: "protect", word: "protect", meaning: "보호하다, 지키다", example: "Protect your morning hour from your phone.", exampleTranslation: "아침 한 시간을 휴대폰으로부터 지켜라.", tags: ["logic"], stage: 1 },
  { id: "prove", word: "prove", meaning: "증명하다, 판명되다", example: "One example cannot prove a general rule.", exampleTranslation: "예시 하나가 일반 규칙을 증명할 수는 없다.", tags: ["logic"], stage: 1 },
  { id: "provide", word: "provide", meaning: "제공하다", example: "The passage provides two clear reasons.", exampleTranslation: "그 지문은 명확한 이유 두 가지를 제공한다.", tags: ["reading"], stage: 1 },
  { id: "publish", word: "publish", meaning: "출판하다, 발표하다", example: "The magazine publishes new stories every month.", exampleTranslation: "그 잡지는 매달 새 이야기를 싣는다.", tags: ["reading"], stage: 1 },
  { id: "punish", word: "punish", meaning: "벌하다, 처벌하다", example: "Do not punish yourself for slow days.", exampleTranslation: "더딘 날들에 대해 자신을 벌하지 마라.", tags: ["listening"], stage: 1 },
  { id: "raise", word: "raise", meaning: "올리다, 기르다, 제기하다", example: "The article raises an important question.", exampleTranslation: "그 기사는 중요한 질문을 제기한다.", tags: ["reading"], stage: 1 },
  { id: "reach", word: "reach", meaning: "도달하다, 닿다", example: "We reach the answer through small steps.", exampleTranslation: "우리는 작은 단계를 거쳐 답에 도달한다.", tags: ["logic"], stage: 1 },
  { id: "realize", word: "realize", meaning: "깨닫다, 실현하다", example: "I realized my mistake after the test.", exampleTranslation: "나는 시험이 끝난 뒤 내 실수를 깨달았다.", tags: ["listening"], stage: 1 },
  { id: "receive", word: "receive", meaning: "받다", example: "She received a letter from her friend.", exampleTranslation: "그녀는 친구에게서 편지를 받았다.", tags: ["reading"], stage: 1 },
  { id: "recognize", word: "recognize", meaning: "알아보다, 인정하다", example: "You will recognize this word next week.", exampleTranslation: "다음 주에는 이 단어를 알아보게 될 것이다.", tags: ["reading"], stage: 1 },
  { id: "recommend", word: "recommend", meaning: "추천하다, 권하다", example: "My teacher recommends ten minutes of listening.", exampleTranslation: "선생님은 10분간의 듣기를 권하신다.", tags: ["listening"], stage: 1 },
  { id: "record", word: "record", meaning: "기록하다, 기록", example: "Record every wrong answer in one place.", exampleTranslation: "모든 오답을 한곳에 기록하라.", tags: ["logic", "writing"], stage: 1 },
  { id: "recover", word: "recover", meaning: "회복하다, 되찾다", example: "Sleep helps the brain recover after study.", exampleTranslation: "잠은 공부 후 뇌가 회복하도록 돕는다.", tags: ["logic"], stage: 1 },
  { id: "refuse", word: "refuse", meaning: "거절하다", example: "He refused the offer without any reason.", exampleTranslation: "그는 아무 이유 없이 그 제안을 거절했다.", tags: ["reading"], stage: 1 },
  { id: "regret", word: "regret", meaning: "후회하다, 후회", example: "You will never regret ten quiet minutes.", exampleTranslation: "조용한 10분을 결코 후회하지 않을 것이다.", tags: ["logic"], stage: 1 },
  { id: "remain", word: "remain", meaning: "남다, 여전히 ~이다", example: "Two questions remain after the first pass.", exampleTranslation: "첫 번째로 훑고 나면 두 문제가 남는다.", tags: ["logic"], stage: 1 },
  { id: "remember", word: "remember", meaning: "기억하다", example: "Remember the sentence, not just the word.", exampleTranslation: "단어만이 아니라 문장을 기억하라.", tags: ["reading"], stage: 1 },
  { id: "remind", word: "remind", meaning: "상기시키다, 떠올리게 하다", example: "This word reminds me of a story.", exampleTranslation: "이 단어는 나에게 한 이야기를 떠올리게 한다.", tags: ["listening"], stage: 1 },
  { id: "remove", word: "remove", meaning: "제거하다, 치우다", example: "Remove your phone from the study desk.", exampleTranslation: "공부 책상에서 휴대폰을 치워라.", tags: ["logic"], stage: 1 },
  { id: "repair", word: "repair", meaning: "수리하다, 수리", example: "He repaired the old bike himself.", exampleTranslation: "그는 낡은 자전거를 직접 수리했다.", tags: ["reading"], stage: 1 },
  { id: "repeat", word: "repeat", meaning: "반복하다", example: "Repeat the same ten words tomorrow.", exampleTranslation: "내일 같은 열 단어를 반복하라.", tags: ["logic"], stage: 1 },
  { id: "replace", word: "replace", meaning: "대체하다, 교체하다", example: "Replace long notes with one clear line.", exampleTranslation: "긴 노트를 명확한 한 줄로 바꿔라.", tags: ["writing"], stage: 1 },
  { id: "reply", word: "reply", meaning: "답하다, 답장", example: "She replied to the email in English.", exampleTranslation: "그녀는 그 이메일에 영어로 답장했다.", tags: ["writing"], stage: 1 },
  { id: "report", word: "report", meaning: "보도하다, 보고서", example: "The news reports a change in weather.", exampleTranslation: "그 뉴스는 날씨의 변화를 보도한다.", tags: ["listening", "reading"], stage: 1 },
  { id: "represent", word: "represent", meaning: "나타내다, 대표하다", example: "This graph represents last year's scores.", exampleTranslation: "이 그래프는 작년 점수를 나타낸다.", tags: ["reading"], stage: 1 },
  { id: "respect", word: "respect", meaning: "존중하다, 존중", example: "Respect your own pace while learning.", exampleTranslation: "배우는 동안 자신의 속도를 존중하라.", tags: ["listening"], stage: 1 },
  { id: "respond", word: "respond", meaning: "응답하다, 반응하다", example: "Respond to the question in one sentence.", exampleTranslation: "그 질문에 한 문장으로 답하라.", tags: ["writing", "listening"], stage: 1 },
  { id: "return", word: "return", meaning: "돌아오다, 반납하다", example: "Return to the hard question at the end.", exampleTranslation: "마지막에 어려운 문제로 돌아와라.", tags: ["logic"], stage: 1 },
  { id: "review", word: "review", meaning: "복습하다, 검토", example: "Review yesterday's words before starting new ones.", exampleTranslation: "새 단어를 시작하기 전에 어제 단어를 복습하라.", tags: ["logic"], stage: 1 },
  { id: "rise", word: "rise", meaning: "오르다, 상승", example: "Prices rise a little every year.", exampleTranslation: "물가는 해마다 조금씩 오른다.", tags: ["reading"], stage: 1 },
  { id: "save", word: "save", meaning: "절약하다, 구하다, 저장하다", example: "A clear plan saves an hour daily.", exampleTranslation: "명확한 계획은 매일 한 시간을 절약해 준다.", tags: ["logic"], stage: 1 },
  { id: "search", word: "search", meaning: "찾다, 검색", example: "Search the passage for the exact word.", exampleTranslation: "지문에서 그 정확한 단어를 찾아라.", tags: ["reading"], stage: 1 },
  { id: "seek", word: "seek", meaning: "찾다, 구하다", example: "Seek help when a topic stays unclear.", exampleTranslation: "주제가 계속 불분명하면 도움을 구하라.", tags: ["logic"], stage: 1 },
  { id: "seem", word: "seem", meaning: "~인 것 같다, ~해 보이다", example: "The passage seems hard at first sight.", exampleTranslation: "그 지문은 처음 보기에는 어려워 보인다.", tags: ["reading"], stage: 1 },
  { id: "select", word: "select", meaning: "고르다, 선발하다", example: "Select one book and finish it completely.", exampleTranslation: "책 한 권을 골라 끝까지 마쳐라.", tags: ["logic"], stage: 1 },
  { id: "sell", word: "sell", meaning: "팔다", example: "The store sells cheap notebooks.", exampleTranslation: "그 가게는 값싼 공책을 판다.", tags: ["listening"], stage: 1 },
  { id: "separate", word: "separate", meaning: "분리하다, 별개의", example: "Separate known words from unknown ones.", exampleTranslation: "아는 단어와 모르는 단어를 분리하라.", tags: ["logic"], stage: 1 },
  { id: "settle", word: "settle", meaning: "해결하다, 정착하다", example: "They settled the argument with clear evidence.", exampleTranslation: "그들은 명확한 근거로 논쟁을 해결했다.", tags: ["reading"], stage: 1 },
  { id: "share", word: "share", meaning: "나누다, 공유하다", example: "Share your notes with a study friend.", exampleTranslation: "공부 친구와 노트를 공유하라.", tags: ["listening"], stage: 1 },
  { id: "shout", word: "shout", meaning: "소리치다, 외침", example: "He shouted my name across the street.", exampleTranslation: "그는 길 건너에서 내 이름을 외쳤다.", tags: ["listening"], stage: 1 },
  { id: "sign", word: "sign", meaning: "징후, 표지, 서명하다", example: "A yawn is a sign of tiredness.", exampleTranslation: "하품은 피곤하다는 신호다.", tags: ["reading"], stage: 1 },
  { id: "solve", word: "solve", meaning: "풀다, 해결하다", example: "Solve three problems slowly and correctly.", exampleTranslation: "세 문제를 천천히 정확하게 풀어라.", tags: ["logic"], stage: 1 },
  { id: "speak", word: "speak", meaning: "말하다", example: "Speak each new word out loud once.", exampleTranslation: "새 단어마다 한 번씩 소리 내어 말하라.", tags: ["listening"], stage: 1 },
  { id: "spend", word: "spend", meaning: "쓰다, 보내다", example: "Spend ten minutes on words each morning.", exampleTranslation: "매일 아침 단어에 10분을 써라.", tags: ["logic"], stage: 1 },
  { id: "spread", word: "spread", meaning: "퍼지다, 펼치다", example: "Rumors spread faster than facts online.", exampleTranslation: "온라인에서는 소문이 사실보다 빨리 퍼진다.", tags: ["reading"], stage: 1 },
  { id: "state", word: "state", meaning: "진술하다, 상태", example: "State your main point in one line.", exampleTranslation: "네 요지를 한 줄로 진술하라.", tags: ["writing"], stage: 1 },
  { id: "steal", word: "steal", meaning: "훔치다", example: "Do not let your phone steal your time.", exampleTranslation: "휴대폰이 네 시간을 훔쳐 가게 두지 마라.", tags: ["logic"], stage: 1 },
  { id: "stick", word: "stick", meaning: "붙이다, 고수하다, 막대기", example: "Stick to the plan for two weeks.", exampleTranslation: "두 주 동안은 그 계획을 고수하라.", tags: ["logic"], stage: 1 },
  { id: "store", word: "store", meaning: "저장하다, 가게", example: "The brain stores words through repeated use.", exampleTranslation: "뇌는 반복 사용을 통해 단어를 저장한다.", tags: ["logic"], stage: 1 },
  { id: "struggle", word: "struggle", meaning: "힘겨워하다, 분투", example: "Many beginners struggle with long sentences.", exampleTranslation: "많은 초보자들이 긴 문장을 힘들어한다.", tags: ["reading"], stage: 1 },
  { id: "succeed", word: "succeed", meaning: "성공하다, 뒤를 잇다", example: "Students succeed by repeating small habits.", exampleTranslation: "학생들은 작은 습관을 반복하며 성공한다.", tags: ["logic"], stage: 1 },
  { id: "suffer", word: "suffer", meaning: "고통받다, 나빠지다", example: "Focus suffers when the room is noisy.", exampleTranslation: "방이 시끄러우면 집중력이 나빠진다.", tags: ["logic"], stage: 1 },
  { id: "supply", word: "supply", meaning: "공급하다, 공급", example: "The teacher supplies a short word list.", exampleTranslation: "선생님이 짧은 단어 목록을 공급해 주신다.", tags: ["reading"], stage: 1 },
  { id: "suppose", word: "suppose", meaning: "가정하다, 생각하다", example: "Suppose the writer is wrong about this.", exampleTranslation: "필자가 이 점에서 틀렸다고 가정해 보라.", tags: ["logic"], stage: 1 },
  { id: "survive", word: "survive", meaning: "살아남다, 견뎌 내다", example: "Only useful habits survive a busy month.", exampleTranslation: "바쁜 한 달을 견디는 것은 쓸모 있는 습관뿐이다.", tags: ["logic"], stage: 1 },
  { id: "teach", word: "teach", meaning: "가르치다", example: "Teaching a friend teaches you twice.", exampleTranslation: "친구를 가르치면 너는 두 배로 배우게 된다.", tags: ["listening"], stage: 1 },
  { id: "threaten", word: "threaten", meaning: "위협하다, 협박하다", example: "Late nights threaten tomorrow's concentration.", exampleTranslation: "늦은 밤은 내일의 집중력을 위협한다.", tags: ["logic"], stage: 1 },
  { id: "throw", word: "throw", meaning: "던지다, 버리다", example: "Do not throw away your old notes.", exampleTranslation: "예전 노트를 버리지 마라.", tags: ["listening"], stage: 1 },
  { id: "train", word: "train", meaning: "훈련하다, 기차", example: "Train your ear with slow English audio.", exampleTranslation: "느린 영어 음원으로 귀를 훈련하라.", tags: ["listening"], stage: 1 },
  { id: "translate", word: "translate", meaning: "번역하다, 옮기다", example: "Translate the sentence after you understand it.", exampleTranslation: "문장을 이해한 다음에 번역하라.", tags: ["reading"], stage: 1 },
  { id: "travel", word: "travel", meaning: "여행하다, 이동하다", example: "Sound travels slower than light.", exampleTranslation: "소리는 빛보다 느리게 이동한다.", tags: ["reading"], stage: 1 },
  { id: "treat", word: "treat", meaning: "다루다, 대하다, 치료하다", example: "Treat every wrong answer as free information.", exampleTranslation: "모든 오답을 공짜 정보로 대하라.", tags: ["logic"], stage: 1 },
  { id: "trust", word: "trust", meaning: "신뢰하다, 신뢰", example: "Trust the passage, not your memory.", exampleTranslation: "네 기억이 아니라 지문을 신뢰하라.", tags: ["reading"], stage: 1 },
  { id: "warn", word: "warn", meaning: "경고하다", example: "The writer warns about easy conclusions.", exampleTranslation: "필자는 성급한 결론에 대해 경고한다.", tags: ["reading"], stage: 1 },
  { id: "waste", word: "waste", meaning: "낭비하다, 쓰레기", example: "Do not waste time on perfect notes.", exampleTranslation: "완벽한 노트를 만드는 데 시간을 낭비하지 마라.", tags: ["logic"], stage: 1 },
  { id: "wonder", word: "wonder", meaning: "궁금해하다, 경이", example: "I wonder why this answer is wrong.", exampleTranslation: "나는 왜 이 답이 틀렸는지 궁금하다.", tags: ["listening"], stage: 1 },
  { id: "worry", word: "worry", meaning: "걱정하다, 걱정", example: "Do not worry about your first score.", exampleTranslation: "첫 점수를 걱정하지 마라.", tags: ["listening"], stage: 1 },
  { id: "attempt", word: "attempt", meaning: "시도하다, 시도", example: "Attempt the question before reading the answer.", exampleTranslation: "해설을 읽기 전에 문제를 먼저 시도하라.", tags: ["logic"], stage: 1 },
  { id: "behave", word: "behave", meaning: "행동하다, 처신하다", example: "Children behave well in a quiet class.", exampleTranslation: "아이들은 조용한 교실에서 얌전히 행동한다.", tags: ["reading"], stage: 1 },
  { id: "bother", word: "bother", meaning: "귀찮게 하다, 신경 쓰다", example: "Small noises bother me during reading.", exampleTranslation: "작은 소음이 독해할 때 나를 방해한다.", tags: ["listening"], stage: 1 },
  { id: "claim", word: "claim", meaning: "주장하다, 주장", example: "The writer claims that sleep improves memory.", exampleTranslation: "필자는 잠이 기억력을 향상시킨다고 주장한다.", tags: ["reading", "logic"], stage: 1 },
  { id: "gain", word: "gain", meaning: "얻다, 증가", example: "You gain speed only after accuracy.", exampleTranslation: "정확성을 갖춘 뒤에야 속도를 얻는다.", tags: ["logic"], stage: 1 },
  { id: "reject", word: "reject", meaning: "거부하다, 거절하다", example: "Reject any choice without textual support.", exampleTranslation: "지문의 뒷받침이 없는 선지는 거부하라.", tags: ["reading", "logic"], stage: 1 },
] as const satisfies readonly VocabWordEntry[];
