export type VocabTag = "reading" | "listening" | "writing" | "logic";

export type VocabWordEntry = {
  id: string;
  word: string;
  meaning: string;
  example: string;
  exampleTranslation: string;
  tags: readonly VocabTag[];
};

export const VOCAB_WORDS: readonly VocabWordEntry[] = [
  { id: "assume", word: "assume", meaning: "가정하다, 추정하다", example: "Do not assume the writer agrees with every example.", exampleTranslation: "필자의 모든 예시에 동의한다고 가정하지 마라.", tags: ["reading", "logic"] },
  { id: "require", word: "require", meaning: "요구하다, 필요로 하다", example: "This question requires careful reading of the final sentence.", exampleTranslation: "이 문제는 마지막 문장을 주의 깊게 읽을 것을 요구한다.", tags: ["reading"] },
  { id: "evidence", word: "evidence", meaning: "근거, 증거", example: "You need evidence to support your answer.", exampleTranslation: "답을 뒷받침할 근거가 필요하다.", tags: ["reading", "writing"] },
  { id: "suggest", word: "suggest", meaning: "시사하다, 암시하다, 제안하다", example: "The data suggest a clear change in behavior.", exampleTranslation: "그 자료는 행동의 뚜렷한 변화를 시사한다.", tags: ["reading", "logic"] },
  { id: "likely", word: "likely", meaning: "~할 것 같은, 가능성 있는", example: "The most likely answer is not always the longest one.", exampleTranslation: "가장 가능성 있는 답이 항상 가장 긴 것은 아니다.", tags: ["reading"] },
  { id: "increase", word: "increase", meaning: "증가하다, 높이다", example: "Regular review can increase memory retention.", exampleTranslation: "규칙적인 복습은 기억 유지력을 높일 수 있다.", tags: ["logic"] },
  { id: "reduce", word: "reduce", meaning: "줄이다, 감소시키다", example: "A simple routine reduces careless mistakes.", exampleTranslation: "단순한 루틴은 부주의한 실수를 줄인다.", tags: ["logic"] },
  { id: "compare", word: "compare", meaning: "비교하다", example: "Compare the two passages before choosing an answer.", exampleTranslation: "답을 고르기 전에 두 지문을 비교하라.", tags: ["reading", "logic"] },
  { id: "contrast", word: "contrast", meaning: "대조하다, 대조", example: "The author contrasts habit with true understanding.", exampleTranslation: "저자는 습관과 진정한 이해를 대조한다.", tags: ["reading", "logic"] },
  { id: "focus", word: "focus", meaning: "집중하다, 초점", example: "Focus on the main claim before reading details.", exampleTranslation: "세부를 읽기 전에 핵심 주장에 집중하라.", tags: ["reading"] },
  { id: "include", word: "include", meaning: "포함하다", example: "The summary should include only essential points.", exampleTranslation: "요약에는 핵심 포인트만 포함되어야 한다.", tags: ["writing"] },
  { id: "essential", word: "essential", meaning: "필수적인, 본질적인", example: "Understanding grammar is essential for reading long sentences.", exampleTranslation: "문법 이해는 긴 문장을 읽는 데 필수적이다.", tags: ["reading"] },
  { id: "concept", word: "concept", meaning: "개념", example: "Master one concept before moving to the next.", exampleTranslation: "다음으로 넘어가기 전에 한 개념을 마스터하라.", tags: ["logic"] },
  { id: "process", word: "process", meaning: "과정, 처리하다", example: "Learning is a gradual process of building confidence.", exampleTranslation: "학습은 자신감을 쌓아가는 점진적인 과정이다.", tags: ["logic"] },
  { id: "result", word: "result", meaning: "결과, ~로 끝나다", example: "Clear practice results in stable scores.", exampleTranslation: "명확한 연습은 안정적인 점수로 이어진다.", tags: ["logic"] },
  { id: "simple", word: "simple", meaning: "단순한, 명쾌한", example: "A simple schedule is easier to continue.", exampleTranslation: "단순한 계획표가 계속하기 더 쉽다.", tags: ["logic"] },
  { id: "context", word: "context", meaning: "맥락, 문맥", example: "The sentence makes sense only in its full context.", exampleTranslation: "그 문장은 전체 맥락 속에서만 의미가 통한다.", tags: ["reading"] },
  { id: "infer", word: "infer", meaning: "추론하다", example: "You can infer the writer's attitude from the final paragraph.", exampleTranslation: "마지막 문단에서 필자의 태도를 추론할 수 있다.", tags: ["reading", "logic"] },
  { id: "derive", word: "derive", meaning: "끌어내다, 유래하다", example: "We can derive the main idea from the first paragraph.", exampleTranslation: "첫 문단에서 중심 생각을 끌어낼 수 있다.", tags: ["reading", "logic"] },
  { id: "distinct", word: "distinct", meaning: "뚜렷한, 별개의", example: "The two solutions have distinct advantages.", exampleTranslation: "두 해결책은 뚜렷이 다른 장점을 가진다.", tags: ["logic"] },
  { id: "factor", word: "factor", meaning: "요인, 요소", example: "Sleep is a major factor in steady study habits.", exampleTranslation: "수면은 꾸준한 공부 습관의 주요 요인이다.", tags: ["logic"] },
  { id: "relevant", word: "relevant", meaning: "관련된, 적절한", example: "Choose only the evidence relevant to the claim.", exampleTranslation: "주장과 관련 있는 근거만 고르라.", tags: ["reading", "logic"] },
  { id: "valid", word: "valid", meaning: "타당한, 유효한", example: "A valid answer must match the passage exactly.", exampleTranslation: "타당한 답은 지문과 정확히 일치해야 한다.", tags: ["reading", "logic"] },
  { id: "conclude", word: "conclude", meaning: "결론짓다", example: "Do not conclude too early from one sentence.", exampleTranslation: "한 문장만 보고 너무 일찍 결론짓지 마라.", tags: ["reading", "logic"] },
  { id: "reflect", word: "reflect", meaning: "반영하다, 숙고하다", example: "Your notes should reflect the text structure.", exampleTranslation: "네 노트는 글의 구조를 반영해야 한다.", tags: ["writing", "reading"] },
  { id: "evaluate", word: "evaluate", meaning: "평가하다, 가치를 가늠하다", example: "Students must evaluate the logical soundness of the argument.", exampleTranslation: "학생들은 주장의 논리적 타당성을 평가해야 한다.", tags: ["reading", "logic"] },
  { id: "illustrate", word: "illustrate", meaning: "설명하다, 예시를 들다", example: "The chart illustrates how energy consumption changes over time.", exampleTranslation: "도표는 시간에 따른 에너지 소비 변화를 보여준다.", tags: ["reading"] },
  { id: "emphasize", word: "emphasize", meaning: "강조하다", example: "The speaker emphasized the importance of daily practice.", exampleTranslation: "강연자는 매일 하는 연습의 중요성을 강조했다.", tags: ["listening", "reading"] },
  { id: "fundamental", word: "fundamental", meaning: "근본적인, 핵심적인", example: "Grammar rules provide the fundamental structure of language.", exampleTranslation: "문법 규칙은 언어의 근본적인 구조를 제공한다.", tags: ["reading"] },
  { id: "perspective", word: "perspective", meaning: "관점, 시각", example: "Try to understand the problem from a different perspective.", exampleTranslation: "다른 관점에서 문제를 이해하려고 시도하라.", tags: ["reading", "logic"] },
  { id: "consequence", word: "consequence", meaning: "결과, 중요성", example: "Every decision in reading has a logical consequence.", exampleTranslation: "독해에서의 모든 판단에는 논리적 결과가 따른다.", tags: ["reading", "logic"] },
  { id: "inevitable", word: "inevitable", meaning: "피할 수 없는, 불가피한", example: "Some mistakes are inevitable during the initial learning phase.", exampleTranslation: "초기 학습 단계에서 몇몇 실수는 피할 수 없다.", tags: ["logic"] },
  { id: "hypothesis", word: "hypothesis", meaning: "가설", example: "Scientists test their hypothesis through repeated experiments.", exampleTranslation: "과학자들은 반복된 실험을 통해 가설을 검증한다.", tags: ["reading", "logic"] },
  { id: "phenomenon", word: "phenomenon", meaning: "현상", example: "Social media is a modern cultural phenomenon.", exampleTranslation: "소셜 미디어는 현대의 문화적 현상이다.", tags: ["reading"] },
  { id: "consistent", word: "consistent", meaning: "일관된, 지속적인", example: "Consistent study brings better results than cramming.", exampleTranslation: "벼락치기보다 일관된 공부가 더 나은 결과를 가져온다.", tags: ["logic"] },
  { id: "significant", word: "significant", meaning: "중요한, 상당한", example: "There is a significant difference between reading and understanding.", exampleTranslation: "그냥 읽는 것과 이해하는 것 사이에는 상당한 차이가 있다.", tags: ["reading", "logic"] },
  { id: "alternative", word: "alternative", meaning: "대안, 대체 가능한", example: "The author proposes an alternative explanation for the trend.", exampleTranslation: "저자는 그 경향에 대해 대안적인 설명을 제시한다.", tags: ["reading", "logic"] },
  { id: "attribute", word: "attribute", meaning: "~의 탓으로 돌리다, 특성", example: "He attributes his success to steady practice.", exampleTranslation: "그는 자신의 성공을 꾸준한 연습 덕분으로 돌린다.", tags: ["reading"] },
  { id: "capacity", word: "capacity", meaning: "수용 능력, 용량", example: "Human memory capacity expands through structured association.", exampleTranslation: "인간의 기억 용량은 구조화된 연상을 통해 확장된다.", tags: ["reading"] },
  { id: "compromise", word: "compromise", meaning: "타협하다, 손상시키다", example: "Never compromise accuracy for speed in early stages.", exampleTranslation: "초기 단계에서 속도를 위해 정확도를 타협하지 마라.", tags: ["logic"] },
  { id: "crucial", word: "crucial", meaning: "중요한, 결정적인", example: "Identifying the main subject is crucial in reading comprehension.", exampleTranslation: "주요 주제를 파악하는 것은 독해에서 결정적이다.", tags: ["reading"] },
  { id: "decline", word: "decline", meaning: "감소하다, 거절하다", example: "Test anxiety tends to decline as preparation increases.", exampleTranslation: "시험 불안은 준비가 늘어남에 따라 줄어드는 경향이 있다.", tags: ["logic"] },
  { id: "demonstrate", word: "demonstrate", meaning: "증명하다, 시연하다", example: "The experiment demonstrates how memory works.", exampleTranslation: "그 실험은 기억이 어떻게 작동하는지 증명한다.", tags: ["reading", "logic"] },
  { id: "determine", word: "determine", meaning: "결정하다, 알아내다", example: "Context helps determine the exact meaning of a word.", exampleTranslation: "문맥은 단어의 정확한 의미를 결정하는 데 도움을 준다.", tags: ["reading"] },
  { id: "dimension", word: "dimension", meaning: "차원, 관점", example: "Literature adds a emotional dimension to language study.", exampleTranslation: "문학은 언어 공부에 감정적 차원을 더해준다.", tags: ["reading"] },
  { id: "dominate", word: "dominate", meaning: "지배하다, 우세를 점하다", example: "One central topic dominates the entire paragraph.", exampleTranslation: "하나의 중심 주제가 문단 전체를 지배한다.", tags: ["reading"] },
  { id: "efficient", word: "efficient", meaning: "효율적인", example: "SRS vocabulary review is an efficient method.", exampleTranslation: "SRS 단어 복습은 효율적인 방법이다.", tags: ["logic"] },
  { id: "eliminate", word: "eliminate", meaning: "제거하다, 오답을 지우다", example: "Eliminate choices that contradict the passage.", exampleTranslation: "지문과 모순되는 선지를 제거하라.", tags: ["reading", "logic"] },
  { id: "encounter", word: "encounter", meaning: "우연히 마주치다, 직면하다", example: "When you encounter a new word, guess its meaning first.", exampleTranslation: "새 단어를 마주쳤을 때, 먼저 의미를 추측해 보라.", tags: ["reading"] },
  { id: "enhance", word: "enhance", meaning: "향상시키다, 강화하다", example: "Reading daily will enhance your vocabulary skills.", exampleTranslation: "매일 읽는 것은 당신의 어휘력을 향상시킬 것이다.", tags: ["reading"] },
  { id: "establish", word: "establish", meaning: "설립하다, 확립하다", example: "Establish a fixed study environment for deep focus.", exampleTranslation: "깊은 집중을 위해 고정된 공부 환경을 확립하라.", tags: ["logic"] },
  { id: "exaggerate", word: "exaggerate", meaning: "과장하다", example: "Do not exaggerate small details when summarizing.", exampleTranslation: "요약할 때 사소한 세부를 과장하지 마라.", tags: ["writing", "reading"] },
  { id: "explicit", word: "explicit", meaning: "명시적인, 뚜렷한", example: "The paragraph gives an explicit warning about errors.", exampleTranslation: "그 문단은 오류에 대해 명시적인 경고를 준다.", tags: ["reading", "logic"] },
  { id: "implicit", word: "implicit", meaning: "암묵적인, 내포된", example: "Identify the implicit assumption behind the author's argument.", exampleTranslation: "저자의 주장 뒤에 숨은 암묵적 가설을 파악하라.", tags: ["reading", "logic"] },
  { id: "imply", word: "imply", meaning: "암시하다, 넌지시 말하다", example: "The passage implies that technology has dual effects.", exampleTranslation: "지문은 기술이 두 가지 효과를 지님을 암시한다.", tags: ["reading"] },
  { id: "indicate", word: "indicate", meaning: "나타내다, 가리키다", example: "The graph indicates a sharp recovery in scores.", exampleTranslation: "그래프는 점수의 급격한 회복을 나타낸다.", tags: ["reading"] },
  { id: "individual", word: "individual", meaning: "개인의, 개별적인", example: "Tailor your study plan to your individual pace.", exampleTranslation: "공부 계획을 자신만의 개인적 속도에 맞추라.", tags: ["logic"] },
  { id: "inefficient", word: "inefficient", meaning: "비효율적인", example: "Rereading without focus is an inefficient study habit.", exampleTranslation: "집중 없이 다시 읽는 것은 비효율적인 공부 습관이다.", tags: ["logic"] },
  { id: "influence", word: "influence", meaning: "영향을 미치다, 영향력", example: "Prior knowledge heavily influences reading comprehension.", exampleTranslation: "배경지식은 독해력에 큰 영향을 미친다.", tags: ["reading"] },
  { id: "insight", word: "insight", meaning: "통찰력, 이해", example: "The article provides deep insight into human cognition.", exampleTranslation: "그 기사는 인간 인지에 대한 깊은 통찰을 제공한다.", tags: ["reading"] },
  { id: "intent", word: "intent", meaning: "의도, 목적", example: "What is the author's main intent in this passage?", exampleTranslation: "이 지문에서 저자의 주된 의도는 무엇인가?", tags: ["reading"] },
  { id: "interpret", word: "interpret", meaning: "해석하다, 이해하다", example: "Learn to interpret data accurately from graphs.", exampleTranslation: "그래프에서 자료를 정확히 해석하는 법을 배워라.", tags: ["reading", "logic"] },
  { id: "investigate", word: "investigate", meaning: "조사하다, 연구하다", example: "Researchers investigate how sleep affects memory.", exampleTranslation: "연구원들은 수면이 기억에 미치는 영향을 조사한다.", tags: ["reading"] },
  { id: "justify", word: "justify", meaning: "정당화하다, 근거를 대다", example: "You must justify your choice using evidence from the text.", exampleTranslation: "글의 근거를 사용해 자신의 선택을 정당화해야 한다.", tags: ["writing", "reading"] },
  { id: "maintain", word: "maintain", meaning: "유지하다, 주장하다", example: "Maintain a steady routine even on weekends.", exampleTranslation: "주말에도 꾸준한 루틴을 유지하라.", tags: ["logic"] },
  { id: "objective", word: "objective", meaning: "객관적인, 목표", example: "Try to stay objective when evaluating arguments.", exampleTranslation: "주장을 평가할 때는 객관성을 유지하려고 노력하라.", tags: ["reading", "logic"] },
  { id: "obtain", word: "obtain", meaning: "얻다, 획득하다", example: "You can obtain key info from titles and topic sentences.", exampleTranslation: "제목과 주제문에서 핵심 정보를 얻을 수 있다.", tags: ["reading"] },
  { id: "opponent", word: "opponent", meaning: "상대, 반대자", example: "The essay addresses potential arguments from opponents.", exampleTranslation: "그 에세이는 반대자들의 잠재적 주장을 다룬다.", tags: ["reading", "logic"] },
  { id: "outcome", word: "outcome", meaning: "결과, 성과", example: "Consistent practice leads to a positive outcome.", exampleTranslation: "일관된 연습은 긍정적인 결과로 이어진다.", tags: ["logic"] },
  { id: "perceive", word: "perceive", meaning: "인지하다, 감각하다", example: "How we perceive difficulty determines our response.", exampleTranslation: "우리가 난이도를 어떻게 인지하느냐가 우리의 반응을 결정한다.", tags: ["reading"] },
  { id: "predict", word: "predict", meaning: "예측하다", example: "Predict the next sentence based on transition words.", exampleTranslation: "접속어를 바탕으로 다음 문장을 예측하라.", tags: ["reading"] },
  { id: "prevalent", word: "prevalent", meaning: "널리 퍼진, 유행하는", example: "Common misconceptions are prevalent among beginners.", exampleTranslation: "흔한 오해들이 초보자들 사이에 널리 퍼져 있다.", tags: ["reading"] },
  { id: "primary", word: "primary", meaning: "주요한, 최초의", example: "The primary cause of failure is hasty guessing.", exampleTranslation: "실패의 주요 원인은 성급한 추측이다.", tags: ["reading", "logic"] },
  { id: "principle", word: "principle", meaning: "원칙, 원리", example: "Understanding basic math principles solves complex problems.", exampleTranslation: "기본 수학 원리를 이해하면 복잡한 문제가 풀린다.", tags: ["logic"] },
  { id: "prompt", word: "prompt", meaning: "신속한, 자극하다, 지문/발문", example: "Read the prompt carefully before reading options.", exampleTranslation: "선지를 읽기 전에 발문을 주의 깊게 읽어라.", tags: ["reading"] },
  { id: "proportion", word: "proportion", meaning: "비율, 부분", example: "A large proportion of questions focus on core concepts.", exampleTranslation: "많은 비율의 문제가 핵심 개념에 집중된다.", tags: ["reading", "logic"] },
  { id: "propose", word: "propose", meaning: "제안하다, 제시하다", example: "The researcher proposed a new method of analysis.", exampleTranslation: "연구자는 새로운 분석 방법을 제안했다.", tags: ["reading"] },
  { id: "reluctant", word: "reluctant", meaning: "꺼리는, 마지못해 하는", example: "Do not be reluctant to review basic grammar.", exampleTranslation: "기초 문법을 복습하는 것을 꺼리지 마라.", tags: ["reading"] },
  { id: "rely", word: "rely", meaning: "의존하다, 신뢰하다", example: "Do not rely solely on memory; write key notes down.", exampleTranslation: "기억에만 의존하지 말고 핵심 노트를 적어라.", tags: ["logic"] },
  { id: "resolve", word: "resolve", meaning: "해결하다, 결심하다", example: "Step-by-step breakdown resolves confusing questions.", exampleTranslation: "단계별 분해는 헷갈리는 문제를 해결해 준다.", tags: ["logic"] },
  { id: "reveal", word: "reveal", meaning: "드러내다, 밝히다", example: "A careful reading reveals the author's hidden view.", exampleTranslation: "주의 깊게 읽으면 저자의 숨은 견해가 드러난다.", tags: ["reading"] },
  { id: "scarce", word: "scarce", meaning: "부족한, 드문", example: "Time is scarce during actual exams, so pace yourself.", exampleTranslation: "실제 시험에서는 시간이 부족하므로 페이스를 조절하라.", tags: ["logic"] },
  { id: "skeptical", word: "skeptical", meaning: "회의적인, 의심하는", example: "Be skeptical of absolute claims containing 'always'.", exampleTranslation: "'항상'을 포함하는 절대적 주장에 회의적인 태도를 가져라.", tags: ["reading", "logic"] },
  { id: "subsequent", word: "subsequent", meaning: "그 다음의, 이어서 일어나는", example: "The first paragraph sets up all subsequent arguments.", exampleTranslation: "첫 문단이 그 뒤 이어지는 모든 주장을 설정한다.", tags: ["reading"] },
  { id: "sufficient", word: "sufficient", meaning: "충분한", example: "Provide sufficient evidence to back up your point.", exampleTranslation: "당신의 주장을 뒷받침할 충분한 근거를 제공하라.", tags: ["writing", "logic"] },
  { id: "support", word: "support", meaning: "지지하다, 뒷받침하다", example: "Every paragraph should support the central thesis.", exampleTranslation: "모든 문단은 중심 논지를 뒷받침해야 한다.", tags: ["reading", "writing"] },
  { id: "tendency", word: "tendency", meaning: "경향, 성향", example: "Students have a tendency to skip basic definitions.", exampleTranslation: "학생들은 기본 정의를 건너뛰는 경향이 있다.", tags: ["logic"] },
  { id: "ultimate", word: "ultimate", meaning: "궁극적인, 최종적인", example: "The ultimate goal is independent problem solving.", exampleTranslation: "궁극적인 목표는 독립적인 문제 해결이다.", tags: ["logic"] },
  { id: "underlie", word: "underlie", meaning: "~의 기저를 이루다", example: "Basic math concepts underlie advanced calculus.", exampleTranslation: "기본 수학 개념이 고등 미적분의 기저를 이룬다.", tags: ["logic"] },
  { id: "undertake", word: "undertake", meaning: "맡다, 착수하다", example: "Undertake a daily review habit for guaranteed growth.", exampleTranslation: "보장된 성장을 위해 매일 복습하는 습관에 착수하라.", tags: ["logic"] },
  { id: "vary", word: "vary", meaning: "다르다, 변하다", example: "Question types vary, but core reading principles stay.", exampleTranslation: "문제 유형은 변하지만 독해의 핵심 원리는 남아있다.", tags: ["reading"] },
  { id: "vital", word: "vital", meaning: "매우 중요한, 필수적인", example: "Focusing on verb tenses is vital for accuracy.", exampleTranslation: "동사 시제에 집중하는 것은 정확성을 위해 매우 중요하다.", tags: ["reading"] },
  { id: "vulnerable", word: "vulnerable", meaning: "취약한", example: "Without vocabulary, your reading strategy is vulnerable.", exampleTranslation: "어휘 없이 독해 전략은 취약해진다.", tags: ["reading"] },
  { id: "yield", word: "yield", meaning: "산출하다, 양보하다", example: "Active note-taking yields higher retention rates.", exampleTranslation: "능동적인 노트 필기는 더 높은 기억 유지율을 낳는다.", tags: ["logic"] },
] as const satisfies readonly VocabWordEntry[];
