export type VocabTag = "reading" | "listening" | "writing" | "logic";

export type VocabWordEntry = {
  id: string;
  word: string;
  meaning: string;
  example: string;
  exampleTranslation: string;
  tags: readonly VocabTag[];
};

export const VOCAB_WORDS: readonly VocabWordEntry[] = [
  {
    id: "assume",
    word: "assume",
    meaning: "가정하다",
    example: "Do not assume the writer agrees with every example.",
    exampleTranslation: "필자의 모든 예시에 동의한다고 가정하지 마라.",
    tags: ["reading", "logic"],
  },
  {
    id: "require",
    word: "require",
    meaning: "요구하다",
    example: "This question requires careful reading of the final sentence.",
    exampleTranslation: "이 문제는 마지막 문장을 주의 깊게 읽을 것을 요구한다.",
    tags: ["reading"],
  },
  {
    id: "evidence",
    word: "evidence",
    meaning: "근거, 증거",
    example: "You need evidence to support your answer.",
    exampleTranslation: "답을 뒷받침할 근거가 필요하다.",
    tags: ["reading", "writing"],
  },
  {
    id: "suggest",
    word: "suggest",
    meaning: "시사하다, 제안하다",
    example: "The data suggest a clear change in behavior.",
    exampleTranslation: "그 자료는 행동의 뚜렷한 변화를 시사한다.",
    tags: ["reading", "logic"],
  },
  {
    id: "likely",
    word: "likely",
    meaning: "그럴듯한, 가능성 있는",
    example: "The most likely answer is not always the longest one.",
    exampleTranslation: "가장 가능성 있는 답이 항상 가장 긴 것은 아니다.",
    tags: ["reading"],
  },
  {
    id: "increase",
    word: "increase",
    meaning: "증가하다, 증가",
    example: "Regular review can increase memory retention.",
    exampleTranslation: "규칙적인 복습은 기억 유지력을 높일 수 있다.",
    tags: ["logic"],
  },
  {
    id: "reduce",
    word: "reduce",
    meaning: "줄이다",
    example: "A simple routine reduces careless mistakes.",
    exampleTranslation: "단순한 루틴은 부주의한 실수를 줄인다.",
    tags: ["logic"],
  },
  {
    id: "compare",
    word: "compare",
    meaning: "비교하다",
    example: "Compare the two passages before choosing an answer.",
    exampleTranslation: "답을 고르기 전에 두 지문을 비교하라.",
    tags: ["reading", "logic"],
  },
  {
    id: "contrast",
    word: "contrast",
    meaning: "대조하다, 대조",
    example: "The author contrasts habit with true understanding.",
    exampleTranslation: "저자는 습관과 진정한 이해를 대조한다.",
    tags: ["reading", "logic"],
  },
  {
    id: "focus",
    word: "focus",
    meaning: "집중하다, 초점",
    example: "Focus on the main claim before reading details.",
    exampleTranslation: "세부를 읽기 전에 핵심 주장에 집중하라.",
    tags: ["reading"],
  },
  {
    id: "include",
    word: "include",
    meaning: "포함하다",
    example: "The summary should include only essential points.",
    exampleTranslation: "요약에는 핵심 포인트만 포함되어야 한다.",
    tags: ["writing"],
  },
  {
    id: "exclude",
    word: "exclude",
    meaning: "제외하다",
    example: "Exclude options that lack textual support.",
    exampleTranslation: "본문 근거가 없는 선택지는 제외하라.",
    tags: ["reading", "logic"],
  },
  {
    id: "determine",
    word: "determine",
    meaning: "판단하다, 결정하다",
    example: "Context helps determine the exact meaning.",
    exampleTranslation: "맥락은 정확한 의미를 판단하는 데 도움이 된다.",
    tags: ["reading", "logic"],
  },
  {
    id: "influence",
    word: "influence",
    meaning: "영향을 주다, 영향",
    example: "Sleep can influence your study performance.",
    exampleTranslation: "수면은 공부 수행에 영향을 줄 수 있다.",
    tags: ["logic"],
  },
  {
    id: "approach",
    word: "approach",
    meaning: "접근법, 접근하다",
    example: "Try a new approach when the old one fails.",
    exampleTranslation: "기존 방식이 실패하면 새로운 접근법을 시도하라.",
    tags: ["logic"],
  },
  {
    id: "specific",
    word: "specific",
    meaning: "구체적인",
    example: "Look for specific clues instead of vague impressions.",
    exampleTranslation: "막연한 인상보다 구체적인 단서를 찾아라.",
    tags: ["reading"],
  },
  {
    id: "general",
    word: "general",
    meaning: "일반적인, 전반적인",
    example: "Read for the general idea before the details.",
    exampleTranslation: "세부보다 먼저 전체적인 생각을 읽어라.",
    tags: ["reading"],
  },
  {
    id: "achieve",
    word: "achieve",
    meaning: "성취하다",
    example: "Small daily goals help you achieve long-term growth.",
    exampleTranslation: "작은 일일 목표는 장기적 성장을 이루게 돕는다.",
    tags: ["logic"],
  },
  {
    id: "improve",
    word: "improve",
    meaning: "향상시키다, 나아지다",
    example: "Repeating short drills improves speed and accuracy.",
    exampleTranslation: "짧은 훈련을 반복하면 속도와 정확도가 향상된다.",
    tags: ["logic"],
  },
  {
    id: "method",
    word: "method",
    meaning: "방법",
    example: "This method works best for basic vocabulary review.",
    exampleTranslation: "이 방법은 기초 어휘 복습에 가장 잘 맞는다.",
    tags: ["logic"],
  },
  {
    id: "benefit",
    word: "benefit",
    meaning: "이점, 혜택",
    example: "One benefit of note-taking is clearer review.",
    exampleTranslation: "필기의 한 가지 이점은 더 선명한 복습이다.",
    tags: ["writing", "logic"],
  },
  {
    id: "result",
    word: "result",
    meaning: "결과",
    example: "Better habits often produce better results.",
    exampleTranslation: "더 나은 습관은 종종 더 나은 결과를 만든다.",
    tags: ["logic"],
  },
  {
    id: "cause",
    word: "cause",
    meaning: "원인, 유발하다",
    example: "Lack of review can cause quick forgetting.",
    exampleTranslation: "복습 부족은 빠른 망각을 유발할 수 있다.",
    tags: ["logic"],
  },
  {
    id: "effect",
    word: "effect",
    meaning: "효과, 결과",
    example: "The effect becomes visible after steady practice.",
    exampleTranslation: "그 효과는 꾸준한 연습 후에 눈에 보인다.",
    tags: ["logic"],
  },
  {
    id: "maintain",
    word: "maintain",
    meaning: "유지하다, 주장하다",
    example: "Maintain a simple routine during busy weeks.",
    exampleTranslation: "바쁜 주간에도 단순한 루틴을 유지하라.",
    tags: ["logic"],
  },
  {
    id: "attention",
    word: "attention",
    meaning: "주의, 집중",
    example: "Pay attention to contrast words like however.",
    exampleTranslation: "however 같은 대조어에 주의를 기울여라.",
    tags: ["reading"],
  },
  {
    id: "feature",
    word: "feature",
    meaning: "특징, 특징으로 삼다",
    example: "The new trainer features short ten-word sessions.",
    exampleTranslation: "새 트레이너는 짧은 10단어 세션을 특징으로 한다.",
    tags: ["logic"],
  },
  {
    id: "avoid",
    word: "avoid",
    meaning: "피하다",
    example: "Avoid rushing before checking the evidence.",
    exampleTranslation: "근거를 확인하기 전에 서두르는 것을 피하라.",
    tags: ["logic"],
  },
  {
    id: "identify",
    word: "identify",
    meaning: "식별하다, 알아내다",
    example: "Identify the subject and verb first.",
    exampleTranslation: "먼저 주어와 동사를 식별하라.",
    tags: ["reading"],
  },
  {
    id: "organize",
    word: "organize",
    meaning: "정리하다, 조직하다",
    example: "Organize words by theme for easier review.",
    exampleTranslation: "더 쉬운 복습을 위해 단어를 주제별로 정리하라.",
    tags: ["writing", "logic"],
  },
  {
    id: "pattern",
    word: "pattern",
    meaning: "패턴, 양상",
    example: "Recognizing a pattern saves time on similar questions.",
    exampleTranslation: "패턴을 알아보면 비슷한 문제에서 시간을 아낀다.",
    tags: ["logic"],
  },
  {
    id: "principle",
    word: "principle",
    meaning: "원리, 원칙",
    example: "The principle is simple: review before you forget.",
    exampleTranslation: "원리는 단순하다. 잊기 전에 복습하라.",
    tags: ["logic"],
  },
  {
    id: "estimate",
    word: "estimate",
    meaning: "추정하다, 추정",
    example: "Estimate the tone before reading each option.",
    exampleTranslation: "각 선택지를 읽기 전에 어조를 추정하라.",
    tags: ["reading", "logic"],
  },
  {
    id: "respond",
    word: "respond",
    meaning: "반응하다, 응답하다",
    example: "Respond to the question, not to your memory alone.",
    exampleTranslation: "기억만이 아니라 문제에 응답하라.",
    tags: ["writing"],
  },
  {
    id: "occur",
    word: "occur",
    meaning: "발생하다",
    example: "Confusion often occurs when you skip key words.",
    exampleTranslation: "핵심 단어를 건너뛰면 혼란이 자주 발생한다.",
    tags: ["logic"],
  },
  {
    id: "complex",
    word: "complex",
    meaning: "복잡한",
    example: "Break complex sentences into smaller parts.",
    exampleTranslation: "복잡한 문장을 더 작은 부분으로 나눠라.",
    tags: ["reading"],
  },
  {
    id: "simple",
    word: "simple",
    meaning: "단순한",
    example: "A simple schedule is easier to continue.",
    exampleTranslation: "단순한 계획표가 계속하기 더 쉽다.",
    tags: ["logic"],
  },
  {
    id: "context",
    word: "context",
    meaning: "맥락",
    example: "The sentence makes sense only in its full context.",
    exampleTranslation: "그 문장은 전체 맥락 속에서만 의미가 통한다.",
    tags: ["reading"],
  },
  {
    id: "infer",
    word: "infer",
    meaning: "추론하다",
    example: "You can infer the writer's attitude from the final paragraph.",
    exampleTranslation: "마지막 문단에서 필자의 태도를 추론할 수 있다.",
    tags: ["reading", "logic"],
  },
  {
    id: "derive",
    word: "derive",
    meaning: "끌어내다, 유래하다",
    example: "We can derive the main idea from the first paragraph.",
    exampleTranslation: "첫 문단에서 중심 생각을 끌어낼 수 있다.",
    tags: ["reading", "logic"],
  },
  {
    id: "distinct",
    word: "distinct",
    meaning: "뚜렷한, 구별되는",
    example: "The two solutions have distinct advantages.",
    exampleTranslation: "두 해결책은 뚜렷이 다른 장점을 가진다.",
    tags: ["logic"],
  },
  {
    id: "factor",
    word: "factor",
    meaning: "요인",
    example: "Sleep is a major factor in steady study habits.",
    exampleTranslation: "수면은 꾸준한 공부 습관의 주요 요인이다.",
    tags: ["logic"],
  },
  {
    id: "relevant",
    word: "relevant",
    meaning: "관련 있는",
    example: "Choose only the evidence relevant to the claim.",
    exampleTranslation: "주장과 관련 있는 근거만 고르라.",
    tags: ["reading", "logic"],
  },
  {
    id: "valid",
    word: "valid",
    meaning: "타당한, 유효한",
    example: "A valid answer must match the passage exactly.",
    exampleTranslation: "타당한 답은 지문과 정확히 일치해야 한다.",
    tags: ["reading", "logic"],
  },
  {
    id: "conclude",
    word: "conclude",
    meaning: "결론짓다",
    example: "Do not conclude too early from one sentence.",
    exampleTranslation: "한 문장만 보고 너무 일찍 결론짓지 마라.",
    tags: ["reading", "logic"],
  },
  {
    id: "reflect",
    word: "reflect",
    meaning: "반영하다, 숙고하다",
    example: "Your notes should reflect the text structure.",
    exampleTranslation: "네 노트는 글의 구조를 반영해야 한다.",
    tags: ["writing", "reading"],
  },
] as const satisfies readonly VocabWordEntry[];
